# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: PACKAGE VERSION\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2021-10-11 21:15+0800\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"Language: \n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"

#: apps/api/base.py:229
#, python-brace-format
msgid "[{module}-API]{error_message}"
msgstr ""

#: apps/api/base.py:298
msgid "返回数据格式不正确，结果格式非json."
msgstr ""

#: apps/api/base.py:367
#, python-brace-format
msgid "[BKLOGAPI] {info}"
msgstr ""

#: apps/api/base.py:787
msgid "请求缺少org_id"
msgstr ""

#: apps/api/modules/bk_itsm.py:29
msgid "ITSM"
msgstr ""

#: apps/api/modules/bk_log.py:29
msgid "log_search元数据"
msgstr ""

#: apps/api/modules/bk_log.py:36
msgid "查询数据"
msgstr ""

#: apps/api/modules/bk_log.py:45
msgid "拉取索引mapping"
msgstr ""

#: apps/api/modules/bk_log.py:53
msgid "查询数据DSL模式"
msgstr ""

#: apps/api/modules/bk_log.py:61
msgid "scroll滚动查询"
msgstr ""

#: apps/api/modules/bk_log.py:69
msgid "获取索引列表"
msgstr ""

#: apps/api/modules/bk_log.py:77
msgid "获取集群信息"
msgstr ""

#: apps/api/modules/bk_log.py:86
msgid "获取kafka采样"
msgstr ""

#: apps/api/modules/bk_log.py:93
msgid "es请求转发"
msgstr ""

#: apps/api/modules/bk_log.py:101
msgid "连通性测试"
msgstr ""

#: apps/api/modules/bk_login.py:54
msgid "PaaS平台登录模块"
msgstr ""

#: apps/api/modules/bk_paas.py:29
msgid "PaaS平台"
msgstr ""

#: apps/api/modules/bkdata_access.py:32
msgid "数据平台接入模块"
msgstr ""

#: apps/api/modules/bkdata_auth.py:32
msgid "数据平台鉴权模块"
msgstr ""

#: apps/api/modules/bkdata_databus.py:29
msgid "计算平台总线模块"
msgstr ""

#: apps/api/modules/bkdata_meta.py:29
msgid "计算平台元数据模块"
msgstr ""

#: apps/api/modules/bkdata_query.py:30
msgid "计算平台数据查询模块"
msgstr ""

#: apps/api/modules/bkdata_storekit.py:29
msgid "数据平台存储模块"
msgstr ""

#: apps/api/modules/cc.py:49 apps/iam/handlers/permission.py:363
msgid "配置平台"
msgstr ""

#: apps/api/modules/cmsi.py:55
msgid "CMSI"
msgstr ""

#: apps/api/modules/gse.py:49
msgid "GSE"
msgstr ""

#: apps/api/modules/gse.py:56
msgid "获取agent状态"
msgstr ""

#: apps/api/modules/iam.py:32
msgid "IAM"
msgstr ""

#: apps/api/modules/job.py:31
msgid "JOB"
msgstr ""

#: apps/api/modules/job.py:37
msgid "快速执行脚本"
msgstr ""

#: apps/api/modules/job.py:44
msgid "快速分发文件"
msgstr ""

#: apps/api/modules/job.py:51
msgid "根据作业id获取执行日志"
msgstr ""

#: apps/api/modules/monitor.py:32
msgid "MONITOR"
msgstr ""

#: apps/api/modules/paascc.py:28
msgid " 蓝鲸 PaaS 3.0 配置中心"
msgstr ""

#: apps/api/modules/transfer.py:79
msgid "Transfer元数据"
msgstr ""

#: apps/api/modules/transfer.py:86
msgid "创建数据源"
msgstr ""

#: apps/api/modules/transfer.py:93
msgid "修改数据源"
msgstr ""

#: apps/api/modules/transfer.py:100
msgid "创建结果表"
msgstr ""

#: apps/api/modules/transfer.py:107
msgid "修改结果表"
msgstr ""

#: apps/api/modules/transfer.py:114
msgid "结果表起停"
msgstr ""

#: apps/api/modules/transfer.py:121
msgid "获取数据源标签"
msgstr ""

#: apps/api/modules/transfer.py:128
msgid "查询一个数据源的ID"
msgstr ""

#: apps/api/modules/transfer.py:135
msgid "查询一个结果表的信息"
msgstr ""

#: apps/api/modules/transfer.py:142
msgid "查询一个结果表的存储信息"
msgstr ""

#: apps/api/modules/transfer.py:150
msgid "查询存储集群列表"
msgstr ""

#: apps/api/modules/transfer.py:158 apps/api/modules/transfer.py:172
msgid "创建存储集群"
msgstr ""

#: apps/api/modules/transfer.py:165
msgid "修改存储集群"
msgstr ""

#: apps/api/modules/transfer.py:179
msgid "获取所有transfer集群信息"
msgstr ""

#: apps/bk_log_admin/constants.py:36
msgid "大于30 s"
msgstr ""

#: apps/bk_log_admin/constants.py:37
msgid "10~30 s"
msgstr ""

#: apps/bk_log_admin/constants.py:38
msgid "0~10 s"
msgstr ""

#: apps/bk_log_admin/exceptions.py:27
msgid "管理端模块异常"
msgstr ""

#: apps/bk_log_admin/exceptions.py:32
msgid "检索历史不存在"
msgstr ""

#: apps/bk_log_admin/exceptions.py:37 apps/exceptions.py:79
msgid "参数验证失败"
msgstr ""

#: apps/bk_log_admin/exceptions.py:42
msgid "获取自定义上报token异常"
msgstr ""

#: apps/bk_log_admin/exceptions.py:47
msgid "获取globalConfig中custom_report_setting 异常"
msgstr ""

#: apps/bk_log_admin/exceptions.py:52
msgid "index_set_id不应该为空"
msgstr ""

#: apps/bk_log_admin/exceptions.py:57
msgid "biz_id or operate_type and operate_id 两组参数必填其中一组"
msgstr ""

#: apps/bk_log_admin/handlers/audit_record.py:34
msgid "空"
msgstr ""

#: apps/bk_log_admin/handlers/audit_record.py:39
msgid "请求内容"
msgstr ""

#: apps/bk_log_admin/views/audit_record_views.py:80
#: apps/log_databus/views/collector_views.py:286
#: apps/log_extract/views/tasks_views.py:119
#: apps/log_search/views/index_set_views.py:259
msgid "分页参数不能为空"
msgstr ""

#: apps/bk_log_admin/views/index_set.py:196
#, python-brace-format
msgid "查询时间段目前只支持{constants.HISTORY_MAX_DAYS}天"
msgstr ""

#: apps/constants.py:32
msgid "邮件"
msgstr ""

#: apps/constants.py:49
msgid "腾讯云对象存储"
msgstr ""

#: apps/constants.py:49
msgid "远程文件系统"
msgstr ""

#: apps/constants.py:70
msgid "采集项"
msgstr ""

#: apps/constants.py:71 apps/log_databus/models.py:245
msgid "存储集群"
msgstr ""

#: apps/constants.py:72 apps/log_measure/handlers/metric_collectors/index.py:31
#: apps/log_measure/handlers/metrics.py:376 apps/log_search/models.py:647
msgid "索引集"
msgstr ""

#: apps/constants.py:73
msgid "检索配置"
msgstr ""

#: apps/constants.py:74 apps/log_databus/models.py:79
#: apps/log_databus/serializers.py:564 apps/log_databus/serializers.py:571
msgid "清洗配置"
msgstr ""

#: apps/constants.py:75
msgid "导出"
msgstr ""

#: apps/constants.py:76
#: apps/log_measure/handlers/metric_collectors/log_extract.py:32
#: apps/log_measure/handlers/metrics.py:583
msgid "日志提取策略"
msgstr ""

#: apps/constants.py:77
msgid "日志提取链路"
msgstr ""

#: apps/constants.py:78
#: apps/log_measure/handlers/metric_collectors/log_extract.py:56
#: apps/log_measure/handlers/metrics.py:605
msgid "日志提取任务"
msgstr ""

#: apps/constants.py:94
msgid "创建"
msgstr ""

#: apps/constants.py:95
msgid "更新"
msgstr ""

#: apps/constants.py:96
msgid "删除"
msgstr ""

#: apps/constants.py:97
msgid "任务重试"
msgstr ""

#: apps/constants.py:98
msgid "启动"
msgstr ""

#: apps/constants.py:99
msgid "停止"
msgstr ""

#: apps/constants.py:100
msgid "新建并替换"
msgstr ""

#: apps/constants.py:101
msgid "替换"
msgstr ""

#: apps/constants.py:102
msgid "配置"
msgstr ""

#: apps/esb/exceptions.py:27
msgid "esb转发模块异常"
msgstr ""

#: apps/esb/exceptions.py:32
msgid "请检查对应请求path"
msgstr ""

#: apps/esb/exceptions.py:37
msgid "该url暂时不支持转发"
msgstr ""

#: apps/esb/exceptions.py:42
msgid "该method暂时不支持"
msgstr ""

#: apps/exceptions.py:49
msgid "系统异常"
msgstr ""

#: apps/exceptions.py:84
msgid "远程服务请求结果异常"
msgstr ""

#: apps/exceptions.py:89
msgid "组件调用异常"
msgstr ""

#: apps/exceptions.py:94
#, python-brace-format
msgid "业务不存在: {bk_biz_id}"
msgstr ""

#: apps/exceptions.py:99
msgid "语言不支持"
msgstr ""

#: apps/exceptions.py:104
msgid "获取锁失败"
msgstr ""

#: apps/exceptions.py:109
msgid "权限不足"
msgstr ""

#: apps/exceptions.py:115
msgid "服务不稳定，请检查组件健康状况"
msgstr ""

#: apps/feature_toggle/models.py:34
msgid "特性开关name"
msgstr ""

#: apps/feature_toggle/models.py:35
msgid "特性开关别名"
msgstr ""

#: apps/feature_toggle/models.py:36
msgid "特性开关status"
msgstr ""

#: apps/feature_toggle/models.py:37
msgid "特性开关描述"
msgstr ""

#: apps/feature_toggle/models.py:38
msgid "是否在前端展示"
msgstr ""

#: apps/feature_toggle/models.py:39
msgid "特性开关配置"
msgstr ""

#: apps/feature_toggle/models.py:40
msgid "业务白名单"
msgstr ""

#: apps/feature_toggle/models.py:43
msgid "日志平台特性开关"
msgstr ""

#: apps/feature_toggle/models.py:44
msgid "41_日志平台特性开关"
msgstr ""

#: apps/generic.py:335 apps/middlewares.py:142
#, python-brace-format
msgid "【APP 自定义异常】{message}, code={code}, args={args}"
msgstr ""

#: apps/generic.py:348
msgid "系统错误，请联系管理员"
msgstr ""

#: apps/grafana/constants.py:27
msgid "主机ID"
msgstr ""

#: apps/grafana/constants.py:28 apps/grafana/constants.py:33
#: apps/grafana/constants.py:35 apps/log_databus/models.py:224
#: apps/log_databus/serializers.py:334 apps/log_databus/serializers.py:460
#: apps/log_search/serializers.py:58
msgid "集群ID"
msgstr ""

#: apps/grafana/constants.py:29 apps/grafana/constants.py:32
msgid "模块ID"
msgstr ""

#: apps/grafana/exceptions.py:27
msgid "Grafana 模块异常"
msgstr ""

#: apps/grafana/exceptions.py:37
msgid "创建Grafana用户失败"
msgstr ""

#: apps/grafana/exceptions.py:42
msgid "获取Grafana用户失败"
msgstr ""

#: apps/grafana/exceptions.py:47
msgid "创建Grafana组织失败"
msgstr ""

#: apps/grafana/exceptions.py:52
msgid "获取Grafana组织失败"
msgstr ""

#: apps/grafana/exceptions.py:57
msgid "获取组织中的用户失败"
msgstr ""

#: apps/grafana/handlers/query.py:52 apps/grafana/handlers/query.py:54
#: apps/log_search/views/search_views.py:656
#: apps/log_search/views/search_views.py:658
msgid "请输入，注意空格符号"
msgstr ""

#: apps/grafana/handlers/query.py:53 apps/grafana/handlers/query.py:55
#: apps/log_search/views/search_views.py:657
#: apps/log_search/views/search_views.py:659
msgid "逗号分隔"
msgstr ""

#: apps/grafana/handlers/query.py:56 apps/grafana/handlers/query.py:57
#: apps/grafana/handlers/query.py:58 apps/grafana/handlers/query.py:59
#: apps/log_search/views/search_views.py:660
#: apps/log_search/views/search_views.py:661
#: apps/log_search/views/search_views.py:662
#: apps/log_search/views/search_views.py:663
msgid "请输入可以支持范围过滤字段相应的值，如整数"
msgstr ""

#: apps/grafana/handlers/query.py:363
msgid "未分类"
msgstr ""

#: apps/grafana/model.py:25
msgid "trace索引集id"
msgstr ""

#: apps/grafana/model.py:26 apps/log_databus/models.py:240
#: apps/log_databus/serializers.py:553
msgid "数据源id"
msgstr ""

#: apps/grafana/provisioning.py:37
msgid "日志平台-时序数据"
msgstr ""

#: apps/grafana/serializers.py:27 apps/grafana/serializers.py:32
#: apps/grafana/serializers.py:38 apps/grafana/serializers.py:47
#: apps/grafana/serializers.py:56 apps/grafana/serializers.py:75
#: apps/grafana/serializers.py:86 apps/log_databus/serializers.py:140
#: apps/log_databus/serializers.py:144 apps/log_databus/serializers.py:170
#: apps/log_databus/serializers.py:294 apps/log_databus/serializers.py:299
#: apps/log_databus/serializers.py:335 apps/log_extract/models.py:45
#: apps/log_extract/serializers.py:60 apps/log_extract/serializers.py:93
#: apps/log_extract/serializers.py:98 apps/log_extract/serializers.py:103
#: apps/log_extract/serializers.py:247 apps/log_extract/serializers.py:325
#: apps/log_extract/serializers.py:373 apps/log_extract/serializers.py:381
#: apps/log_search/models.py:155 apps/log_search/models.py:561
#: apps/log_search/serializers.py:57 apps/log_search/serializers.py:145
#: apps/log_search/serializers.py:198 apps/log_search/serializers.py:352
#: apps/log_trace/serializers.py:40 apps/log_trace/serializers.py:52
msgid "业务ID"
msgstr ""

#: apps/grafana/serializers.py:28 apps/grafana/serializers.py:33
msgid "查询类型"
msgstr ""

#: apps/grafana/serializers.py:34
msgid "查询参数"
msgstr ""

#: apps/grafana/serializers.py:39 apps/log_databus/serializers.py:177
msgid "分类ID"
msgstr ""

#: apps/grafana/serializers.py:48 apps/log_extract/serializers.py:382
#: apps/log_search/serializers.py:302
msgid "实例类型"
msgstr ""

#: apps/grafana/serializers.py:49 apps/log_extract/serializers.py:383
#: apps/log_search/serializers.py:303
msgid "是否删除空节点"
msgstr ""

#: apps/grafana/serializers.py:53 apps/grafana/serializers.py:72
msgid "仪表盘ID"
msgstr ""

#: apps/grafana/serializers.py:54 apps/grafana/serializers.py:73
msgid "面板ID"
msgstr ""

#: apps/grafana/serializers.py:57
msgid "监控指标"
msgstr ""

#: apps/grafana/serializers.py:58 apps/grafana/serializers.py:76
#: apps/grafana/serializers.py:87 apps/log_databus/models.py:78
#: apps/log_databus/serializers.py:456
msgid "结果表ID"
msgstr ""

#: apps/grafana/serializers.py:59 apps/grafana/serializers.py:77
msgid "过滤条件"
msgstr ""

#: apps/grafana/serializers.py:60
msgid "聚合字段"
msgstr ""

#: apps/grafana/serializers.py:61 apps/grafana/serializers.py:78
#: apps/grafana/serializers.py:91
msgid "查询字符串"
msgstr ""

#: apps/grafana/serializers.py:63
msgid "聚合方法"
msgstr ""

#: apps/grafana/serializers.py:64
msgid "时间间隔"
msgstr ""

#: apps/grafana/serializers.py:65 apps/grafana/serializers.py:79
msgid "监控目标"
msgstr ""

#: apps/grafana/serializers.py:67 apps/grafana/serializers.py:81
#: apps/grafana/serializers.py:89 apps/grafana/serializers.py:101
#: apps/log_extract/serializers.py:65 apps/log_trace/constants.py:71
#: apps/log_trace/handlers/trace_field_handlers.py:44
#: apps/log_trace/handlers/trace_field_handlers.py:51
msgid "开始时间"
msgstr ""

#: apps/grafana/serializers.py:68 apps/grafana/serializers.py:82
#: apps/grafana/serializers.py:90 apps/grafana/serializers.py:102
#: apps/log_extract/serializers.py:66 apps/log_search/serializers.py:253
msgid "结束时间"
msgstr ""

#: apps/grafana/serializers.py:80
msgid "日志条数"
msgstr ""

#: apps/grafana/serializers.py:88
msgid "查询字段"
msgstr ""

#: apps/grafana/serializers.py:95
msgid "operation"
msgstr ""

#: apps/grafana/serializers.py:96
msgid "service"
msgstr ""

#: apps/grafana/serializers.py:97
msgid "tags"
msgstr ""

#: apps/grafana/serializers.py:98
msgid "minDuration"
msgstr ""

#: apps/grafana/serializers.py:99
msgid "maxDuration"
msgstr ""

#: apps/grafana/serializers.py:100
msgid "limit"
msgstr ""

#: apps/iam/exceptions.py:52
#, python-brace-format
msgid "当前用户无 [{action_name}] 权限"
msgstr ""

#: apps/iam/handlers/actions.py:213
#, python-brace-format
msgid "动作ID不存在：{action_id}"
msgstr ""

#: apps/iam/handlers/permission.py:306
#, python-brace-format
msgid "获取系统信息错误：{message}"
msgstr ""

#: apps/iam/handlers/resources.py:212
#, python-brace-format
msgid "资源ID不存在：{resource_id}"
msgstr ""

#: apps/log_audit/models.py:27
msgid "操作时间"
msgstr ""

#: apps/log_audit/models.py:28
msgid "操作者"
msgstr ""

#: apps/log_audit/models.py:29 apps/log_databus/models.py:67
#: apps/log_databus/models.py:199 apps/log_databus/models.py:213
#: apps/log_databus/models.py:223 apps/log_databus/models.py:247
#: apps/log_databus/models.py:263 apps/log_databus/models.py:277
#: apps/log_databus/serializers.py:534 apps/log_databus/serializers.py:538
#: apps/log_databus/serializers.py:552 apps/log_databus/serializers.py:557
#: apps/log_databus/serializers.py:566 apps/log_databus/serializers.py:573
#: apps/log_extract/components/collections/distribution_component.py:46
#: apps/log_extract/components/collections/packing_component.py:50
#: apps/log_extract/models.py:74 apps/log_search/serializers.py:249
#: apps/log_search/serializers.py:314
msgid "业务id"
msgstr ""

#: apps/log_audit/models.py:30
msgid "操作对象类型"
msgstr ""

#: apps/log_audit/models.py:31
msgid "操作对象子类型"
msgstr ""

#: apps/log_audit/models.py:32
msgid "操作对象id"
msgstr ""

#: apps/log_audit/models.py:33
msgid "操作方法"
msgstr ""

#: apps/log_audit/models.py:34
msgid "请求参数"
msgstr ""

#: apps/log_audit/models.py:37 apps/log_audit/models.py:38
msgid "操作日志"
msgstr ""

#: apps/log_databus/constants.py:39
#: apps/log_measure/handlers/metric_collectors/cluster.py:87
#: apps/log_measure/handlers/metrics.py:481
msgid "集群节点"
msgstr ""

#: apps/log_databus/constants.py:39
#: apps/log_measure/handlers/metric_collectors/collect.py:61
msgid "采集项容量"
msgstr ""

#: apps/log_databus/constants.py:49
msgid "未申请采集接入"
msgstr ""

#: apps/log_databus/constants.py:50
msgid "采集接入进行中"
msgstr ""

#: apps/log_databus/constants.py:51
msgid "采集接入失败"
msgstr ""

#: apps/log_databus/constants.py:52
msgid "采集接入完成"
msgstr ""

#: apps/log_databus/constants.py:95
msgid "微秒（microsecond）"
msgstr ""

#: apps/log_databus/constants.py:131 apps/log_search/constants.py:231
#: apps/log_search/constants.py:395
msgid "主机"
msgstr ""

#: apps/log_databus/constants.py:132
msgid "服务实例"
msgstr ""

#: apps/log_databus/constants.py:147
msgid "TOPO"
msgstr ""

#: apps/log_databus/constants.py:148
msgid "主机实例"
msgstr ""

#: apps/log_databus/constants.py:149
msgid "服务模板"
msgstr ""

#: apps/log_databus/constants.py:150
msgid "集群模板"
msgstr ""

#: apps/log_databus/constants.py:163
msgid "Transfer"
msgstr ""

#: apps/log_databus/constants.py:164
#: apps/log_search/migrations/0002_bklog_initial.py:37
#: apps/log_search/models.py:139
msgid "数据平台"
msgstr ""

#: apps/log_databus/constants.py:206
msgid "部署中"
msgstr ""

#: apps/log_databus/constants.py:207 apps/log_search/constants.py:146
#: apps/log_search/constants.py:206 apps/log_search/handlers/index_set.py:168
#: apps/log_search/models.py:554
msgid "正常"
msgstr ""

#: apps/log_databus/constants.py:208 apps/log_extract/constants.py:85
#: apps/log_trace/handlers/proto/log.py:35
msgid "失败"
msgstr ""

#: apps/log_databus/constants.py:209
msgid "部分失败"
msgstr ""

#: apps/log_databus/constants.py:210
msgid "已停用"
msgstr ""

#: apps/log_databus/constants.py:211
msgid "未知"
msgstr ""

#: apps/log_databus/constants.py:212
msgid "准备中"
msgstr ""

#: apps/log_databus/exceptions.py:32
msgid "采集配置模块异常"
msgstr ""

#: apps/log_databus/exceptions.py:37
msgid "采集配置不存在"
msgstr ""

#: apps/log_databus/exceptions.py:42
msgid "链路配置不存在"
msgstr ""

#: apps/log_databus/exceptions.py:47
msgid "参数校验异常：采集项ID不存在"
msgstr ""

#: apps/log_databus/exceptions.py:52
msgid "参数校验异常：采集任务ID不存在"
msgstr ""

#: apps/log_databus/exceptions.py:57
msgid "参数校验异常：采集实例ID不存在"
msgstr ""

#: apps/log_databus/exceptions.py:62
msgid "采集项名称已存在"
msgstr ""

#: apps/log_databus/exceptions.py:67
msgid "数据链路ID不存在"
msgstr ""

#: apps/log_databus/exceptions.py:72
msgid "无法查询到该订阅配置信息"
msgstr ""

#: apps/log_databus/exceptions.py:77
msgid "采集项在停止状态下不能编辑"
msgstr ""

#: apps/log_databus/exceptions.py:82
msgid "采集项已存在正在部署中的任务，请不要重复部署"
msgstr ""

#: apps/log_databus/exceptions.py:87
#, python-brace-format
msgid "创建或更新节点管理订阅配置异常{err}"
msgstr ""

#: apps/log_databus/exceptions.py:92
#, python-brace-format
msgid "创建数据平台异常{err}"
msgstr ""

#: apps/log_databus/exceptions.py:97
#, python-brace-format
msgid "采集项包含非该业务【{bk_biz_id}】IP，异常IP列表为: {illegal_ips}"
msgstr ""

#: apps/log_databus/exceptions.py:102
#, python-brace-format
msgid "采集项{collector_config_name_en}英文名重复"
msgstr ""

#: apps/log_databus/exceptions.py:107 apps/log_measure/exceptions.py:37
msgid "集群不存在"
msgstr ""

#: apps/log_databus/exceptions.py:112
msgid "bk_biz_id为必填字段，且为整数"
msgstr ""

#: apps/log_databus/exceptions.py:117 apps/log_esquery/exceptions.py:31
#: apps/log_search/exceptions.py:30
msgid "权限异常"
msgstr ""

#: apps/log_databus/exceptions.py:122
msgid "集群连接异常"
msgstr ""

#: apps/log_databus/exceptions.py:127
#, python-brace-format
msgid "集群连接异常, 异常信息{info}"
msgstr ""

#: apps/log_databus/exceptions.py:132 apps/log_esquery/exceptions.py:121
#, python-brace-format
msgid "未知的ES服务端版本类型\"{ip}\":\"{port}\""
msgstr ""

#: apps/log_databus/exceptions.py:137
#, python-brace-format
msgid "http探测ES版本错误, \"{msg}\""
msgstr ""

#: apps/log_databus/exceptions.py:142
msgid "集群不支持冷热数据功能"
msgstr ""

#: apps/log_databus/exceptions.py:147
#, python-brace-format
msgid "暫不支持{separator_node_action}类清洗"
msgstr ""

#: apps/log_databus/exceptions.py:152
msgid "分隔符配置解析异常"
msgstr ""

#: apps/log_databus/exceptions.py:157
msgid "字段提取预览失败，请检查提取规则与数据是否匹配"
msgstr ""

#: apps/log_databus/exceptions.py:162
msgid "解析数据时间字段异常"
msgstr ""

#: apps/log_databus/exceptions.py:167
msgid "解析时间格式异常"
msgstr ""

#: apps/log_databus/exceptions.py:172
msgid "字段名总长度超过256，暂不支持"
msgstr ""

#: apps/log_databus/exceptions.py:177
msgid "该业务已超出公共集群容量限制"
msgstr ""

#: apps/log_databus/exceptions.py:182
msgid "该数据链路名已被使用"
msgstr ""

#: apps/log_databus/exceptions.py:187
msgid "数据链路kafka、transfer集群不可修改，es集群不可删除"
msgstr ""

#: apps/log_databus/exceptions.py:192
msgid "无法匹配到行首，请确认"
msgstr ""

#: apps/log_databus/exceptions.py:197
#, python-brace-format
msgid "正则表达式不合法: \"{error}\" 请确认"
msgstr ""

#: apps/log_databus/exceptions.py:202
#, python-brace-format
msgid "kafka连接失败\"{error}\""
msgstr ""

#: apps/log_databus/exceptions.py:207
msgid "Partition信息获取失败"
msgstr ""

#: apps/log_databus/exceptions.py:212
msgid "数据链路配置获取失败"
msgstr ""

#: apps/log_databus/exceptions.py:217
msgid "采集接入ITSM-TOKEN非法"
msgstr ""

#: apps/log_databus/exceptions.py:222
msgid "已经提交采集接入申请"
msgstr ""

#: apps/log_databus/exceptions.py:227
msgid "采集接入ITSM流程服务不存在"
msgstr ""

#: apps/log_databus/exceptions.py:232
msgid "采集接入流程未完成，无法启动采集"
msgstr ""

#: apps/log_databus/exceptions.py:237
msgid "采集接入未完成"
msgstr ""

#: apps/log_databus/exceptions.py:242
msgid "后台bkdata_id_feature不存在"
msgstr ""

#: apps/log_databus/exceptions.py:247
#, python-brace-format
msgid "清洗模板{clean_template_id}不存在"
msgstr ""

#: apps/log_databus/exceptions.py:252
#, python-brace-format
msgid "该业务 {bk_biz} 已存在该模板{name}"
msgstr ""

#: apps/log_databus/exceptions.py:257
#, python-brace-format
msgid "该业务{bk_biz_id}未找到对应project"
msgstr ""

#: apps/log_databus/handlers/collector.py:163
msgid "ES索引主分片大小达到{}G后分裂"
msgstr ""

#: apps/log_databus/handlers/collector.py:469
#: apps/log_databus/handlers/etl.py:179
msgid "[采集项]"
msgstr ""

#: apps/log_databus/handlers/collector.py:1489 apps/log_search/constants.py:170
#: apps/log_search/handlers/biz.py:163 config/default.py:539
msgid "集群"
msgstr ""

#: apps/log_databus/handlers/collector.py:1495 apps/log_search/constants.py:171
#: apps/log_search/handlers/biz.py:169
msgid "模块"
msgstr ""

#: apps/log_databus/handlers/collector_scenario/base.py:107
msgid "创建采集项时名称不能为空"
msgstr ""

#: apps/log_databus/handlers/etl_storage/base.py:127
msgid "字段不能与标准字段重复"
msgstr ""

#: apps/log_databus/handlers/etl_storage/base.py:130
msgid "字段名不符合变量规则"
msgstr ""

#: apps/log_databus/handlers/etl_storage/bk_log_delimiter.py:51
msgid "分隔符不能为空"
msgstr ""

#: apps/log_databus/handlers/etl_storage/bk_log_regexp.py:42
msgid "正则表达式不能为空"
msgstr ""

#: apps/log_databus/handlers/etl_storage/bk_log_regexp.py:47
msgid "无法匹配正则表达式"
msgstr ""

#: apps/log_databus/handlers/etl_storage/bk_log_regexp.py:76
msgid "字段未在正则表达式中定义："
msgstr ""

#: apps/log_databus/handlers/etl_storage/utils/transfer.py:66
msgid "separator_field_list类型不符合"
msgstr ""

#: apps/log_databus/handlers/storage.py:527
msgid "IP or PORT can not be reached"
msgstr ""

#: apps/log_databus/handlers/storage.py:531
#, python-format
msgid "IP or PORT can not be reached, %s"
msgstr ""

#: apps/log_databus/models.py:63
msgid "采集配置ID"
msgstr ""

#: apps/log_databus/models.py:64
msgid "采集配置名称"
msgstr ""

#: apps/log_databus/models.py:65 apps/log_search/models.py:156
msgid "接入的来源APP"
msgstr ""

#: apps/log_databus/models.py:66 apps/log_search/constants.py:254
msgid "采集场景"
msgstr ""

#: apps/log_databus/models.py:68 apps/log_search/constants.py:253
#: apps/log_search/models.py:282
msgid "数据分类"
msgstr ""

#: apps/log_databus/models.py:69
msgid "对象类型"
msgstr ""

#: apps/log_databus/models.py:70 apps/log_databus/serializers.py:179
#: apps/log_databus/serializers.py:205
msgid "节点类型"
msgstr ""

#: apps/log_databus/models.py:71 apps/log_databus/serializers.py:241
#: apps/log_databus/serializers.py:278 apps/log_databus/serializers.py:290
msgid "采集目标"
msgstr ""

#: apps/log_databus/models.py:72
msgid "与上一次采集订阅的差异"
msgstr ""

#: apps/log_databus/models.py:73 apps/log_databus/serializers.py:409
#: apps/log_search/models.py:158
msgid "描述"
msgstr ""

#: apps/log_databus/models.py:74 apps/log_databus/models.py:203
#: apps/log_search/models.py:295
msgid "是否可用"
msgstr ""

#: apps/log_databus/models.py:75
msgid "采集链路id"
msgstr ""

#: apps/log_databus/models.py:76
msgid "采集链路data_id"
msgstr ""

#: apps/log_databus/models.py:77
msgid "采集链路data_name"
msgstr ""

#: apps/log_databus/models.py:80
msgid "节点管理订阅ID"
msgstr ""

#: apps/log_databus/models.py:81
msgid "最后一次部署任务"
msgstr ""

#: apps/log_databus/models.py:82
msgid "接入数据平台data id"
msgstr ""

#: apps/log_databus/models.py:83 apps/log_databus/models.py:248
#: apps/log_search/models.py:693 apps/log_search/models.py:749
msgid "索引集id"
msgstr ""

#: apps/log_databus/models.py:84 apps/log_databus/serializers.py:181
#: apps/log_databus/serializers.py:207
msgid "日志字符集"
msgstr ""

#: apps/log_databus/models.py:85
msgid "params"
msgstr ""

#: apps/log_databus/models.py:86
msgid "itsm单据号"
msgstr ""

#: apps/log_databus/models.py:88
msgid "采集接入单据状态"
msgstr ""

#: apps/log_databus/models.py:90
msgid "是否能够使用独立es集群"
msgstr ""

#: apps/log_databus/models.py:91
msgid "采集打包数量"
msgstr ""

#: apps/log_databus/models.py:92
msgid "输出格式"
msgstr ""

#: apps/log_databus/models.py:93
msgid "采集器配置覆盖"
msgstr ""

#: apps/log_databus/models.py:94
msgid "ES分片数量"
msgstr ""

#: apps/log_databus/models.py:95
msgid "单shards分片大小"
msgstr ""

#: apps/log_databus/models.py:96
msgid "ES副本数"
msgstr ""

#: apps/log_databus/models.py:97
msgid "调用数据平台创建data_id失败数"
msgstr ""

#: apps/log_databus/models.py:98
msgid "采集项英文名"
msgstr ""

#: apps/log_databus/models.py:130 apps/log_databus/models.py:131
msgid "用户采集配置"
msgstr ""

#: apps/log_databus/models.py:170
msgid "【日志采集】{}-{}-{}"
msgstr ""

#: apps/log_databus/models.py:197 apps/log_databus/serializers.py:295
msgid "链路ID"
msgstr ""

#: apps/log_databus/models.py:198 apps/log_databus/serializers.py:312
#: apps/log_databus/serializers.py:358
msgid "集群名称"
msgstr ""

#: apps/log_databus/models.py:200
msgid "kafka集群ID"
msgstr ""

#: apps/log_databus/models.py:201
msgid "transfer集群ID"
msgstr ""

#: apps/log_databus/models.py:202
msgid "es集群ID"
msgstr ""

#: apps/log_databus/models.py:204 apps/log_databus/serializers.py:158
#: apps/log_extract/models.py:104 apps/log_extract/serializers.py:108
#: apps/log_extract/serializers.py:236 apps/log_extract/serializers.py:387
msgid "备注"
msgstr ""

#: apps/log_databus/models.py:207 apps/log_databus/models.py:208
msgid "数据链路配置"
msgstr ""

#: apps/log_databus/models.py:214
msgid "容量"
msgstr ""

#: apps/log_databus/models.py:217
msgid "公共集群容量限制"
msgstr ""

#: apps/log_databus/models.py:218
msgid "存储集群容量限制"
msgstr ""

#: apps/log_databus/models.py:225
msgid "已用容量"
msgstr ""

#: apps/log_databus/models.py:228 apps/log_databus/models.py:229
msgid "业务已用容量"
msgstr ""

#: apps/log_databus/models.py:235 apps/log_trace/constants.py:92
#: apps/log_trace/handlers/trace_field_handlers.py:49
#: apps/log_trace/handlers/trace_field_handlers.py:178
msgid "状态"
msgstr ""

#: apps/log_databus/models.py:236
msgid "状态英文名"
msgstr ""

#: apps/log_databus/models.py:237
msgid "结果表id"
msgstr ""

#: apps/log_databus/models.py:238 bk_monitor/models.py:12
msgid "结果表名"
msgstr ""

#: apps/log_databus/models.py:239
msgid "结果表中文名"
msgstr ""

#: apps/log_databus/models.py:241 apps/log_search/models.py:219
#: bk_monitor/models.py:10
msgid "数据源名称"
msgstr ""

#: apps/log_databus/models.py:242
msgid "数据源中文名"
msgstr ""

#: apps/log_databus/models.py:243
msgid "数据类型"
msgstr ""

#: apps/log_databus/models.py:244
msgid "存储类型"
msgstr ""

#: apps/log_databus/models.py:246
msgid "采集项id"
msgstr ""

#: apps/log_databus/models.py:249
msgid "索引集是否被授权"
msgstr ""

#: apps/log_databus/models.py:252 apps/log_databus/models.py:253
msgid "高级清洗列表"
msgstr ""

#: apps/log_databus/models.py:258
msgid "清洗id"
msgstr ""

#: apps/log_databus/models.py:259 apps/log_search/models.py:767
msgid "模板名"
msgstr ""

#: apps/log_databus/models.py:260 apps/log_databus/models.py:273
msgid "模板类型"
msgstr ""

#: apps/log_databus/models.py:261 apps/log_databus/models.py:274
msgid "etl配置"
msgstr ""

#: apps/log_databus/models.py:262 apps/log_databus/models.py:275
msgid "etl字段"
msgstr ""

#: apps/log_databus/models.py:266 apps/log_databus/models.py:267
#: config/default.py:485
msgid "清洗模板"
msgstr ""

#: apps/log_databus/models.py:272
msgid "清洗缓存id"
msgstr ""

#: apps/log_databus/models.py:276
msgid "采集项列表"
msgstr ""

#: apps/log_databus/models.py:280 apps/log_databus/models.py:281
msgid "未完成入库暂存清洗"
msgstr ""

#: apps/log_databus/serializers.py:42
msgid "管理组id列表"
msgstr ""

#: apps/log_databus/serializers.py:43
msgid "可见人员列表"
msgstr ""

#: apps/log_databus/serializers.py:51 apps/log_databus/serializers.py:61
msgid "分类标识"
msgstr ""

#: apps/log_databus/serializers.py:52 apps/log_databus/serializers.py:62
msgid "分类名称"
msgstr ""

#: apps/log_databus/serializers.py:71
msgid "服务实例id"
msgstr ""

#: apps/log_databus/serializers.py:72
msgid "节点实例id"
msgstr ""

#: apps/log_databus/serializers.py:73
msgid "节点对象"
msgstr ""

#: apps/log_databus/serializers.py:74 apps/log_databus/serializers.py:237
msgid "主机实例ip"
msgstr ""

#: apps/log_databus/serializers.py:75 apps/log_databus/serializers.py:238
msgid "蓝鲸云区域id"
msgstr ""

#: apps/log_databus/serializers.py:76 apps/log_databus/serializers.py:239
msgid "供应商id"
msgstr ""

#: apps/log_databus/serializers.py:80
msgid "匹配项所在位置"
msgstr ""

#: apps/log_databus/serializers.py:81
msgid "匹配值"
msgstr ""

#: apps/log_databus/serializers.py:82
msgid "匹配方式"
msgstr ""

#: apps/log_databus/serializers.py:83
msgid "逻辑操作符"
msgstr ""

#: apps/log_databus/serializers.py:91
msgid "过滤方式类型"
msgstr ""

#: apps/log_databus/serializers.py:93
#: apps/log_databus/views/collector_views.py:196
#: apps/log_databus/views/collector_views.py:217
#: apps/tests/log_databus/test_e2e_collectorviewsetapi.py:69
#: apps/tests/log_databus/test_e2e_collectorviewsetapi.py:90
msgid "过滤方式"
msgstr ""

#: apps/log_databus/serializers.py:100
#: apps/log_extract/components/collections/packing_component.py:54
#: apps/log_extract/models.py:79 apps/log_extract/serializers.py:343
msgid "过滤内容"
msgstr ""

#: apps/log_databus/serializers.py:103 apps/log_databus/serializers.py:382
#: apps/log_search/constants.py:297 apps/log_search/constants.py:484
msgid "分隔符"
msgstr ""

#: apps/log_databus/serializers.py:105
msgid "过滤规则"
msgstr ""

#: apps/log_databus/serializers.py:114
msgid "过滤分隔符不能为空"
msgstr ""

#: apps/log_databus/serializers.py:124
#: apps/log_databus/views/collector_views.py:189
#: apps/log_databus/views/collector_views.py:210
#: apps/tests/log_databus/test_e2e_collectorviewsetapi.py:62
#: apps/tests/log_databus/test_e2e_collectorviewsetapi.py:83
msgid "日志路径"
msgstr ""

#: apps/log_databus/serializers.py:126
msgid "行首正则"
msgstr ""

#: apps/log_databus/serializers.py:127
msgid "最多匹配行数"
msgstr ""

#: apps/log_databus/serializers.py:128
msgid "最大耗时"
msgstr ""

#: apps/log_databus/serializers.py:129
msgid "是否增量采集"
msgstr ""

#: apps/log_databus/serializers.py:130
msgid "文件扫描忽略时间"
msgstr ""

#: apps/log_databus/serializers.py:131
msgid "单行日志最大长度"
msgstr ""

#: apps/log_databus/serializers.py:133
msgid "文件扫描间隔"
msgstr ""

#: apps/log_databus/serializers.py:134
msgid "FD关联间隔"
msgstr ""

#: apps/log_databus/serializers.py:135
msgid "同时采集数"
msgstr ""

#: apps/log_databus/serializers.py:136
msgid "采集进度清理时间"
msgstr ""

#: apps/log_databus/serializers.py:152
msgid "链路集群名称"
msgstr ""

#: apps/log_databus/serializers.py:153
msgid "链路允许的业务id"
msgstr ""

#: apps/log_databus/serializers.py:154
msgid "kafka集群id"
msgstr ""

#: apps/log_databus/serializers.py:155
msgid "transfer集群id"
msgstr ""

#: apps/log_databus/serializers.py:156
msgid "es集群id"
msgstr ""

#: apps/log_databus/serializers.py:157 apps/log_extract/models.py:202
#: apps/log_extract/serializers.py:433
msgid "是否启用"
msgstr ""

#: apps/log_databus/serializers.py:162
msgid "集群种类"
msgstr ""

#: apps/log_databus/serializers.py:171 apps/log_databus/serializers.py:200
msgid "采集名称"
msgstr ""

#: apps/log_databus/serializers.py:173 apps/log_databus/serializers.py:202
msgid "采集英文名称"
msgstr ""

#: apps/log_databus/serializers.py:175
msgid "数据链路id"
msgstr ""

#: apps/log_databus/serializers.py:176
msgid "日志类型"
msgstr ""

#: apps/log_databus/serializers.py:178 apps/log_databus/serializers.py:204
msgid "目标类型"
msgstr ""

#: apps/log_databus/serializers.py:180 apps/log_databus/serializers.py:206
msgid "目标节点"
msgstr ""

#: apps/log_databus/serializers.py:183 apps/log_databus/serializers.py:209
msgid "备注说明"
msgstr ""

#: apps/log_databus/serializers.py:191
msgid "{} 该字段为必填项"
msgstr ""

#: apps/log_databus/serializers.py:245
msgid "采集项ID"
msgstr ""

#: apps/log_databus/serializers.py:249
msgid "collector_id_list不符合格式，采集项ID（多个ID用半角,分隔）"
msgstr ""

#: apps/log_databus/serializers.py:254
msgid "部署任务ID"
msgstr ""

#: apps/log_databus/serializers.py:261
msgid "task_id_list不符合格式，部署任务ID（多个ID用半角,分隔）"
msgstr ""

#: apps/log_databus/serializers.py:266 apps/log_extract/serializers.py:244
msgid "实例ID"
msgstr ""

#: apps/log_databus/serializers.py:267
#: apps/log_extract/components/collections/distribution_component.py:42
#: apps/log_extract/components/collections/packing_component.py:47
msgid "任务ID"
msgstr ""

#: apps/log_databus/serializers.py:277
msgid "数据分类名称"
msgstr ""

#: apps/log_databus/serializers.py:279
msgid "任务ID列表"
msgstr ""

#: apps/log_databus/serializers.py:280
msgid "订阅目标变更情况"
msgstr ""

#: apps/log_databus/serializers.py:281
msgid "是否可以创建基础清洗"
msgstr ""

#: apps/log_databus/serializers.py:282
msgid "数据平台索引集id列表"
msgstr ""

#: apps/log_databus/serializers.py:303
#: apps/log_extract/components/collections/distribution_component.py:44
#: apps/log_extract/components/collections/packing_component.py:52
#: version_log/models.py:42
msgid "用户名"
msgstr ""

#: apps/log_databus/serializers.py:304 apps/log_databus/serializers.py:340
msgid "密码"
msgstr ""

#: apps/log_databus/serializers.py:313 apps/log_databus/serializers.py:336
#: apps/log_databus/serializers.py:359
msgid "集群域名"
msgstr ""

#: apps/log_databus/serializers.py:314
msgid "集群端口"
msgstr ""

#: apps/log_databus/serializers.py:315 apps/log_databus/serializers.py:338
#: apps/log_databus/serializers.py:361
msgid "集群协议"
msgstr ""

#: apps/log_databus/serializers.py:316 apps/log_databus/serializers.py:343
#: apps/log_databus/serializers.py:362
msgid "凭据信息"
msgstr ""

#: apps/log_databus/serializers.py:317 apps/log_databus/serializers.py:363
msgid "是否开启冷热数据"
msgstr ""

#: apps/log_databus/serializers.py:318 apps/log_databus/serializers.py:364
msgid "热节点属性名称"
msgstr ""

#: apps/log_databus/serializers.py:319 apps/log_databus/serializers.py:365
msgid "热节点属性值"
msgstr ""

#: apps/log_databus/serializers.py:320 apps/log_databus/serializers.py:366
msgid "冷节点属性名称"
msgstr ""

#: apps/log_databus/serializers.py:321 apps/log_databus/serializers.py:367
msgid "冷节点属性值"
msgstr ""

#: apps/log_databus/serializers.py:329 apps/log_databus/serializers.py:375
msgid "当冷热数据处于开启状态时，冷热节点属性配置不能为空"
msgstr ""

#: apps/log_databus/serializers.py:337 apps/log_databus/serializers.py:360
msgid "端口"
msgstr ""

#: apps/log_databus/serializers.py:339 templates/admin/login.html:12
#: templates/admin/login.html:14
msgid "用户"
msgstr ""

#: apps/log_databus/serializers.py:341
msgid "是否包含集群信息"
msgstr ""

#: apps/log_databus/serializers.py:342
msgid "是否使用默认用户信息"
msgstr ""

#: apps/log_databus/serializers.py:380 apps/log_search/constants.py:298
msgid "正则表达式"
msgstr ""

#: apps/log_databus/serializers.py:384
msgid "是否保留原文"
msgstr ""

#: apps/log_databus/serializers.py:388 apps/log_databus/serializers.py:457
#: apps/log_databus/serializers.py:563 apps/log_databus/serializers.py:570
msgid "清洗类型"
msgstr ""

#: apps/log_databus/serializers.py:390
msgid "日志内容"
msgstr ""

#: apps/log_databus/serializers.py:394
msgid "日志样例"
msgstr ""

#: apps/log_databus/serializers.py:395
msgid "行首正则表达式"
msgstr ""

#: apps/log_databus/serializers.py:399 apps/log_search/constants.py:260
msgid "时间格式"
msgstr ""

#: apps/log_databus/serializers.py:400 apps/log_search/models.py:157
msgid "时区"
msgstr ""

#: apps/log_databus/serializers.py:401
msgid "时间内容"
msgstr ""

#: apps/log_databus/serializers.py:405
msgid "字段顺序"
msgstr ""

#: apps/log_databus/serializers.py:406
msgid "字段名称"
msgstr ""

#: apps/log_databus/serializers.py:407
msgid "别名"
msgstr ""

#: apps/log_databus/serializers.py:408 apps/log_trace/handlers/proto/otlp.py:63
msgid "类型"
msgstr ""

#: apps/log_databus/serializers.py:410
msgid "是否分词"
msgstr ""

#: apps/log_databus/serializers.py:411
msgid "是否维度"
msgstr ""

#: apps/log_databus/serializers.py:412
msgid "是否时间字段"
msgstr ""

#: apps/log_databus/serializers.py:413 apps/models.py:261
msgid "是否删除"
msgstr ""

#: apps/log_databus/serializers.py:414
msgid "是否内置字段"
msgstr ""

#: apps/log_databus/serializers.py:415 apps/log_databus/serializers.py:459
#: apps/log_databus/serializers.py:565 apps/log_databus/serializers.py:572
#: apps/log_search/models.py:580
msgid "字段配置"
msgstr ""

#: apps/log_databus/serializers.py:421
msgid "参数不能为空：field_name/field_type"
msgstr ""

#: apps/log_databus/serializers.py:426
msgid "字段别名不能与标准字段重复"
msgstr ""

#: apps/log_databus/serializers.py:428
msgid "字段名称不能与标准字段重复"
msgstr ""

#: apps/log_databus/serializers.py:439
msgid "只有字符串类型的字段才可以设置为分词"
msgstr ""

#: apps/log_databus/serializers.py:444
msgid "时间字段需配置时区、格式"
msgstr ""

#: apps/log_databus/serializers.py:448 apps/log_databus/serializers.py:451
msgid "时间字段类型与格式不匹配"
msgstr ""

#: apps/log_databus/serializers.py:461
msgid "有效时间"
msgstr ""

#: apps/log_databus/serializers.py:462
msgid "冷热数据生效时间"
msgstr ""

#: apps/log_databus/serializers.py:463 apps/log_search/models.py:290
msgid "查看权限"
msgstr ""

#: apps/log_databus/serializers.py:470
msgid "[字段提取]请输入需要提取的字段信息"
msgstr ""

#: apps/log_databus/serializers.py:474
msgid "存储索引名不能包含bklog关键字"
msgstr ""

#: apps/log_databus/serializers.py:489
msgid "分隔符必须指定field_index"
msgstr ""

#: apps/log_databus/serializers.py:498
msgid "仅可以设置一个时间字段"
msgstr ""

#: apps/log_databus/serializers.py:501
msgid "清洗需要配置有效字段"
msgstr ""

#: apps/log_databus/serializers.py:509
msgid "itsm单号"
msgstr ""

#: apps/log_databus/serializers.py:510
msgid "itsm单据标题"
msgstr ""

#: apps/log_databus/serializers.py:511
msgid "itsm单据地址"
msgstr ""

#: apps/log_databus/serializers.py:512
msgid "itsm单据状态"
msgstr ""

#: apps/log_databus/serializers.py:513
msgid "itsm最近更新者"
msgstr ""

#: apps/log_databus/serializers.py:514
msgid "itsm最近更新时间"
msgstr ""

#: apps/log_databus/serializers.py:515
msgid "itsm审批结果"
msgstr ""

#: apps/log_databus/serializers.py:516
msgid "itsmtoken"
msgstr ""

#: apps/log_databus/serializers.py:520
msgid "期待接入日期"
msgstr ""

#: apps/log_databus/serializers.py:521
msgid "单条日志大小(bytes)"
msgstr ""

#: apps/log_databus/serializers.py:522
msgid "单机流量峰值（kB/S）"
msgstr ""

#: apps/log_databus/serializers.py:523
msgid "单机增长日志量"
msgstr ""

#: apps/log_databus/serializers.py:524
msgid "预计接入主机数"
msgstr ""

#: apps/log_databus/serializers.py:525
msgid "日志保留天数"
msgstr ""

#: apps/log_databus/serializers.py:526
msgid "热数据天数"
msgstr ""

#: apps/log_databus/serializers.py:527
msgid "申请原因"
msgstr ""

#: apps/log_databus/serializers.py:531
msgid "内网ip"
msgstr ""

#: apps/log_databus/serializers.py:532
msgid "云区域Id"
msgstr ""

#: apps/log_databus/serializers.py:533
msgid "主机id"
msgstr ""

#: apps/log_databus/serializers.py:539
msgid "检索关键词"
msgstr ""

#: apps/log_databus/serializers.py:540
msgid "清洗配置类型"
msgstr ""

#: apps/log_databus/serializers.py:541 apps/log_search/serializers.py:45
msgid "页码"
msgstr ""

#: apps/log_databus/serializers.py:542
msgid "页面大小"
msgstr ""

#: apps/log_databus/serializers.py:547
msgid "分页参数不能为负数"
msgstr ""

#: apps/log_databus/serializers.py:558
msgid "是否是轮询请求"
msgstr ""

#: apps/log_databus/serializers.py:562
msgid "清洗模板名"
msgstr ""

#: apps/log_databus/views/collector_views.py:183
#: apps/log_search/constants.py:304
#: apps/tests/log_databus/test_e2e_collectorviewsetapi.py:56
msgid "行日志"
msgstr ""

#: apps/log_databus/views/collector_views.py:204
#: apps/log_search/constants.py:305
#: apps/tests/log_databus/test_e2e_collectorviewsetapi.py:77
msgid "段日志"
msgstr ""

#: apps/log_esquery/esquery/client/QueryClientEs.py:121
#: apps/log_esquery/esquery/client/QueryClientLog.py:130
#: apps/log_search/exceptions.py:68
msgid "EsClient链接失败"
msgstr ""

#: apps/log_esquery/esquery/client/QueryClientLog.py:271
msgid "结果表不存在"
msgstr ""

#: apps/log_esquery/exceptions.py:36
#, python-format, python-brace-format
msgid "查询的接入类型\"{scenario_id}\"不在接入范围%s"
msgstr ""

#: apps/log_esquery/exceptions.py:41
msgid "请输入索引集ID"
msgstr ""

#: apps/log_esquery/exceptions.py:46
msgid "此接口暂未对外，请确认"
msgstr ""

#: apps/log_esquery/exceptions.py:56
msgid "场景类型异常"
msgstr ""

#: apps/log_esquery/exceptions.py:61
#, python-brace-format
msgid ""
"该索引\"{result_table_id}\"不存在，所在的scenario_id不存在\"{scenario_id}\""
msgstr ""

#: apps/log_esquery/exceptions.py:66
#, python-brace-format
msgid "该索引所在的scenario_id不唯一\"{scenario_id_list}\""
msgstr ""

#: apps/log_esquery/exceptions.py:71
msgid "scenario空异常"
msgstr ""

#: apps/log_esquery/exceptions.py:76
#, python-brace-format
msgid "该索引所在的source_id不唯一\"{source_id_list}\""
msgstr ""

#: apps/log_esquery/exceptions.py:81
msgid ""
"存储集群ID(storage_cluster_id)信息空异常，当查询场景（scenario_id）不是bkdata"
"时候需要传入正确的storage_cluster_id"
msgstr ""

#: apps/log_esquery/exceptions.py:86
#, python-brace-format
msgid "该索引\"{result_table_id}\"不存在，所在的Source_id不存在\"{source_id}\""
msgstr ""

#: apps/log_esquery/exceptions.py:91
#, python-brace-format
msgid ""
"该索引\"{result_table_id}\"所在查询场景\"{scenario_id}\"与查询连接信息所需场"
"景不匹配"
msgstr ""

#: apps/log_esquery/exceptions.py:101
msgid "时间异常"
msgstr ""

#: apps/log_esquery/exceptions.py:106
msgid "时间字段空异常"
msgstr ""

#: apps/log_esquery/exceptions.py:116 apps/log_esquery/exceptions.py:131
msgid "客户端版本异常"
msgstr ""

#: apps/log_esquery/exceptions.py:136
msgid "缺少连接ES的账号密码"
msgstr ""

#: apps/log_esquery/exceptions.py:141
#, python-brace-format
msgid "连接ES错误\"{error}\""
msgstr ""

#: apps/log_esquery/exceptions.py:146
#, python-brace-format
msgid "加载EsClient客户端失败，场景\"{scenario_id}\"，版本\"{version}"
msgstr ""

#: apps/log_esquery/exceptions.py:151
#, python-brace-format
msgid "EsClient查询错误\"{error}\""
msgstr ""

#: apps/log_esquery/exceptions.py:156
#, python-brace-format
msgid "原生ES主机\"{host}\"和端口\"{port}错误\""
msgstr ""

#: apps/log_esquery/exceptions.py:161
#, python-brace-format
msgid "从meta获取连接信息失败{message}"
msgstr ""

#: apps/log_esquery/exceptions.py:166
#, python-brace-format
msgid "EsClient scroll查询错误\"{error}\""
msgstr ""

#: apps/log_esquery/exceptions.py:171
#, python-brace-format
msgid "EsClient Alias查询错误\"{error}\""
msgstr ""

#: apps/log_esquery/exceptions.py:176
#, python-brace-format
msgid "EsClient cat indices查询错误\"{error}\""
msgstr ""

#: apps/log_esquery/exceptions.py:181
msgid "EsClient 查询错误"
msgstr ""

#: apps/log_esquery/exceptions.py:186
msgid "Es 查询超时"
msgstr ""

#: apps/log_esquery/exceptions.py:196 apps/log_trace/exceptions.py:30
msgid "查询异常"
msgstr ""

#: apps/log_esquery/exceptions.py:201 apps/log_search/exceptions.py:291
msgid "构建查询参数失败"
msgstr ""

#: apps/log_esquery/exceptions.py:206
#, python-brace-format
msgid "拉取ES字段失败, ERROR: \"{error}\""
msgstr ""

#: apps/log_esquery/exceptions.py:211
#, python-brace-format
msgid "查询上下文场景错误, ERROR Scenario_id is : \"{scenario_id}\""
msgstr ""

#: apps/log_esquery/exceptions.py:216
#, python-brace-format
msgid "查询DSL错误, ERROR DSL is : \"{dsl}\""
msgstr ""

#: apps/log_esquery/exceptions.py:221 apps/log_search/exceptions.py:286
#, python-brace-format
msgid "索引集【{index_set_id}】没有已审批通过的索引信息"
msgstr ""

#: apps/log_esquery/exceptions.py:226 apps/log_search/exceptions.py:236
#, python-brace-format
msgid "找不到索引集\"{index_set_id}\"的相关信息"
msgstr ""

#: apps/log_esquery/exceptions.py:231
#, python-brace-format
msgid "找不到索引集\"{index_set_id}\"的相关信息time_field信息"
msgstr ""

#: apps/log_esquery/serializers.py:52
msgid "是否包含开始时间点(gte/gt)"
msgstr ""

#: apps/log_esquery/serializers.py:53
msgid "是否包含结束时间点(lte/lt)"
msgstr ""

#: apps/log_esquery/serializers.py:112 apps/log_esquery/serializers.py:314
#: apps/log_esquery/serializers.py:353
msgid "第三方ES需传集群ID：storage_cluster_id"
msgstr ""

#: apps/log_esquery/serializers.py:118
msgid "请提供时间字段"
msgstr ""

#: apps/log_esquery/serializers.py:184 apps/log_esquery/serializers.py:222
#: apps/log_esquery/serializers.py:241 apps/log_esquery/serializers.py:293
msgid "indices该字段是必填项"
msgstr ""

#: apps/log_esquery/serializers.py:203
msgid "bk_biz_id该字段是必填项"
msgstr ""

#: apps/log_esquery/serializers.py:205 apps/log_esquery/serializers.py:224
#: apps/log_esquery/serializers.py:243 apps/log_esquery/serializers.py:275
#: apps/log_esquery/serializers.py:295
msgid "storage_cluster_id该字段是必填项"
msgstr ""

#: apps/log_esquery/serializers.py:248
msgid "转发的url"
msgstr ""

#: apps/log_esquery/serializers.py:259
msgid "非法的url路径"
msgstr ""

#: apps/log_esquery/serializers.py:277
msgid "indices 该字段是必填项"
msgstr ""

#: apps/log_extract/admin.py:70 apps/log_extract/models.py:191
#: apps/log_extract/serializers.py:409 apps/log_extract/serializers.py:426
msgid "链路类型"
msgstr ""

#: apps/log_extract/components/collections/base_component.py:43
#, python-brace-format
msgid "开始{name}"
msgstr ""

#: apps/log_extract/components/collections/base_component.py:47
#: apps/log_extract/components/collections/base_component.py:78
#, python-brace-format
msgid "{name}失败"
msgstr ""

#: apps/log_extract/components/collections/base_component.py:54
#: apps/log_extract/components/collections/base_component.py:82
#, python-brace-format
msgid "[{name}] {reason}"
msgstr ""

#: apps/log_extract/components/collections/base_component.py:56
#: apps/log_extract/components/collections/base_component.py:84
#, python-brace-format
msgid "{name}失败: {reason}"
msgstr ""

#: apps/log_extract/components/collections/base_component.py:74
#, python-brace-format
msgid "开始轮询结果：{name}"
msgstr ""

#: apps/log_extract/components/collections/cos_upload_component.py:32
msgid "Cos 文件上传"
msgstr ""

#: apps/log_extract/components/collections/cos_upload_component.py:41
msgid "job instance id"
msgstr ""

#: apps/log_extract/components/collections/cos_upload_component.py:42
msgid "pack file name"
msgstr ""

#: apps/log_extract/components/collections/cos_upload_component.py:92
msgid "Cos Upload 正在执行中"
msgstr ""

#: apps/log_extract/components/collections/cos_upload_component.py:97
msgid "上传网盘异常: {}"
msgstr ""

#: apps/log_extract/components/collections/distribution_component.py:33
msgid "文件分发"
msgstr ""

#: apps/log_extract/components/collections/distribution_component.py:43
msgid "源文件信息列表"
msgstr ""

#: apps/log_extract/components/collections/distribution_component.py:45
#: apps/log_extract/components/collections/packing_component.py:56
msgid "执行脚本机器的用户名"
msgstr ""

#: apps/log_extract/components/collections/distribution_component.py:47
#: apps/log_extract/components/collections/packing_component.py:51
#: apps/log_extract/models.py:52 apps/log_extract/serializers.py:285
msgid "作业执行人"
msgstr ""

#: apps/log_extract/components/collections/distribution_component.py:52
msgid "分发任务instance id"
msgstr ""

#: apps/log_extract/components/collections/distribution_component.py:53
msgid "分发服务器IP地址"
msgstr ""

#: apps/log_extract/components/collections/distribution_component.py:54
msgid "分发服务器中转文件路径"
msgstr ""

#: apps/log_extract/components/collections/distribution_component.py:55
msgid "分发后打包步骤的打包路径"
msgstr ""

#: apps/log_extract/components/collections/distribution_component.py:70
#: apps/log_extract/serializers.py:131
msgid "提取链路不存在"
msgstr ""

#: apps/log_extract/components/collections/distribution_component.py:75
msgid "请配置链路中转服务器"
msgstr ""

#: apps/log_extract/components/collections/distribution_component.py:114
#: apps/log_extract/components/collections/packing_component.py:155
msgid "脚本正在执行中"
msgstr ""

#: apps/log_extract/components/collections/distribution_component.py:120
msgid "文件分发异常({})"
msgstr ""

#: apps/log_extract/components/collections/packing_component.py:38
msgid "文件打包"
msgstr ""

#: apps/log_extract/components/collections/packing_component.py:48
#: apps/log_extract/models.py:76 apps/log_extract/serializers.py:330
#: apps/log_extract/serializers.py:340
msgid "文件列表"
msgstr ""

#: apps/log_extract/components/collections/packing_component.py:49
msgid "目标ip列表"
msgstr ""

#: apps/log_extract/components/collections/packing_component.py:53
#: apps/log_extract/models.py:78 apps/log_extract/serializers.py:106
#: apps/log_extract/serializers.py:342
msgid "过滤类型"
msgstr ""

#: apps/log_extract/components/collections/packing_component.py:55
msgid "打包路径"
msgstr ""

#: apps/log_extract/components/collections/packing_component.py:61
msgid "任务实例ID"
msgstr ""

#: apps/log_extract/components/collections/packing_component.py:62
msgid "task输出内容"
msgstr ""

#: apps/log_extract/components/collections/packing_component.py:63
msgid "打包后的文件路径"
msgstr ""

#: apps/log_extract/components/collections/packing_component.py:64
msgid "上传的服务器IP"
msgstr ""

#: apps/log_extract/components/collections/packing_component.py:165
msgid "目标机器没有足够的储存"
msgstr ""

#: apps/log_extract/components/collections/packing_component.py:170
msgid "任务打包异常: {}"
msgstr ""

#: apps/log_extract/constants.py:45
msgid "初始化"
msgstr ""

#: apps/log_extract/constants.py:46
msgid "初始化任务调度"
msgstr ""

#: apps/log_extract/constants.py:47
msgid "文件打包中"
msgstr ""

#: apps/log_extract/constants.py:48
msgid "文件分发中"
msgstr ""

#: apps/log_extract/constants.py:49
msgid "分发文件打包中"
msgstr ""

#: apps/log_extract/constants.py:50
msgid "文件上传中"
msgstr ""

#: apps/log_extract/constants.py:51 apps/log_extract/handlers/tasks.py:226
msgid "分发到网盘中"
msgstr ""

#: apps/log_extract/constants.py:52
msgid "已完成"
msgstr ""

#: apps/log_extract/constants.py:53
msgid "已过期"
msgstr ""

#: apps/log_extract/constants.py:54
msgid "文件提取异常"
msgstr ""

#: apps/log_extract/constants.py:68
msgid "按关键字过滤行"
msgstr ""

#: apps/log_extract/constants.py:69
msgid "按行数过滤"
msgstr ""

#: apps/log_extract/constants.py:70
msgid "获取最新n行"
msgstr ""

#: apps/log_extract/constants.py:71
msgid "按关键字范围过滤行"
msgstr ""

#: apps/log_extract/constants.py:83
msgid "未执行"
msgstr ""

#: apps/log_extract/constants.py:84
msgid "执行中"
msgstr ""

#: apps/log_extract/constants.py:86
msgid "暂停"
msgstr ""

#: apps/log_extract/constants.py:87
msgid "已经终止"
msgstr ""

#: apps/log_extract/constants.py:88
msgid "已经结束"
msgstr ""

#: apps/log_extract/constants.py:102
msgid "与"
msgstr ""

#: apps/log_extract/constants.py:103
msgid "或"
msgstr ""

#: apps/log_extract/constants.py:104
msgid "非"
msgstr ""

#: apps/log_extract/constants.py:115
msgid "按topo选择目标"
msgstr ""

#: apps/log_extract/constants.py:115
msgid "按module选择目标"
msgstr ""

#: apps/log_extract/constants.py:124 apps/log_extract/constants.py:127
msgid "内网链路"
msgstr ""

#: apps/log_extract/constants.py:124
msgid "腾讯云cos链路"
msgstr ""

#: apps/log_extract/constants.py:136
msgid "近一天"
msgstr ""

#: apps/log_extract/constants.py:136
msgid "近一周"
msgstr ""

#: apps/log_extract/constants.py:136
msgid "近一月"
msgstr ""

#: apps/log_extract/constants.py:136
msgid "所有"
msgstr ""

#: apps/log_extract/constants.py:136
msgid "自定义"
msgstr ""

#: apps/log_extract/exceptions.py:27
msgid "日志提取模块异常"
msgstr ""

#: apps/log_extract/exceptions.py:32
msgid "请配置云石账密信息"
msgstr ""

#: apps/log_extract/exceptions.py:37
msgid "请配置中转服务器信息"
msgstr ""

#: apps/log_extract/exceptions.py:42
msgid "该Task ID 不存在"
msgstr ""

#: apps/log_extract/exceptions.py:47 apps/log_extract/exceptions.py:167
#, python-brace-format
msgid "拉取topo结构失败：{error}, 请求参数：{params} "
msgstr ""

#: apps/log_extract/exceptions.py:52
#, python-brace-format
msgid "获取全部topo为空,请求参数：{params} "
msgstr ""

#: apps/log_extract/exceptions.py:57
msgid "获取任务详情失败，您不是该任务的创建者"
msgstr ""

#: apps/log_extract/exceptions.py:62
#, python-brace-format
msgid ""
"选择文件不可下载，请确认所配置策略，不可下载文件：{failed_download_file_list}"
msgstr ""

#: apps/log_extract/exceptions.py:67
msgid "重新创建任务失败，您不是原任务的创建者"
msgstr ""

#: apps/log_extract/exceptions.py:72
msgid "禁止删除任务！"
msgstr ""

#: apps/log_extract/exceptions.py:77 apps/log_extract/exceptions.py:112
#, python-brace-format
msgid "{message}"
msgstr ""

#: apps/log_extract/exceptions.py:82
msgid "当前任务已过期"
msgstr ""

#: apps/log_extract/exceptions.py:87
msgid "当前任务已达最大下载次数"
msgstr ""

#: apps/log_extract/exceptions.py:92
msgid "创建任务异常"
msgstr ""

#: apps/log_extract/exceptions.py:97
msgid "当前任务不可下载"
msgstr ""

#: apps/log_extract/exceptions.py:102
msgid "下载任务失败，您没有此任务的下载权限"
msgstr ""

#: apps/log_extract/exceptions.py:107
msgid "更新任务信息失败，你不是此任务的创建者"
msgstr ""

#: apps/log_extract/exceptions.py:117
msgid "请管理员配置提取链路"
msgstr ""

#: apps/log_extract/exceptions.py:122
msgid "提取链路不存在，请管理员检查"
msgstr ""

#: apps/log_extract/exceptions.py:127
msgid "下载目标文件不存在"
msgstr ""

#: apps/log_extract/exceptions.py:132
#, python-brace-format
msgid "访问{request_dir}目录错误，请检查是否已授权"
msgstr ""

#: apps/log_extract/exceptions.py:137
msgid "用户获取可访问目录失败，请重新选择服务器"
msgstr ""

#: apps/log_extract/exceptions.py:142
#, python-brace-format
msgid "未对用户授权模块{request_module}"
msgstr ""

#: apps/log_extract/exceptions.py:147
msgid "文件或目录不存在"
msgstr ""

#: apps/log_extract/exceptions.py:152
msgid "所选服务器器中同时包含windows与linux，请重新选择服务器"
msgstr ""

#: apps/log_extract/exceptions.py:157
#, python-brace-format
msgid "存在{mismatch_number}个服务器无对应TOPO，请重新选择服务器"
msgstr ""

#: apps/log_extract/exceptions.py:162
msgid "所选择的服务器授权目录或文件后缀无交集，请重新选择服务器"
msgstr ""

#: apps/log_extract/exceptions.py:172
#, python-brace-format
msgid "获取topo为空,请求参数：{params} "
msgstr ""

#: apps/log_extract/exceptions.py:177
msgid "暂无权限访问此页面,请联系管理员"
msgstr ""

#: apps/log_extract/exceptions.py:182
msgid "过滤topo为空,请检查策略配置"
msgstr ""

#: apps/log_extract/exceptions.py:187
msgid "预览文件超时，请重试"
msgstr ""

#: apps/log_extract/exceptions.py:192
msgid "文件预览异常"
msgstr ""

#: apps/log_extract/exceptions.py:197
#, python-brace-format
msgid "ID为{strategy_id}的策略不存在!"
msgstr ""

#: apps/log_extract/exceptions.py:202
msgid "参数异常：策略ID不存在"
msgstr ""

#: apps/log_extract/exceptions.py:207
msgid "该业务下已存在相同的策略名"
msgstr ""

#: apps/log_extract/exceptions.py:212
msgid "您在该业务下尚未拥有下载策略，联系业务运维进行下载策略授权"
msgstr ""

#: apps/log_extract/exceptions.py:217
msgid "您在该业务下尚未拥有下载策略，请先通过'管理-日志提取配置'添加策略"
msgstr ""

#: apps/log_extract/exceptions.py:222
msgid "策略执行人配置不合法"
msgstr ""

#: apps/log_extract/exceptions.py:227
msgid "该用户组不存在"
msgstr ""

#: apps/log_extract/exceptions.py:232
#, python-brace-format
msgid "搜索文件失败,失败原因: {message}"
msgstr ""

#: apps/log_extract/exceptions.py:237
#, python-brace-format
msgid " {message}"
msgstr ""

#: apps/log_extract/exceptions.py:243
#, python-brace-format
msgid ""
"[periodic_clear_timeout_pipeline_task]撤销超时pipeline任务失败：{exceptions} "
"task_id=>{task_id}, pipeline_id=>{pipeline_id}"
msgstr ""

#: apps/log_extract/exceptions.py:250
msgid "查找的日志提取链路不存在"
msgstr ""

#: apps/log_extract/exceptions.py:255
msgid "查找的日志提取链路type不支持"
msgstr ""

#: apps/log_extract/exceptions.py:260
msgid "不能修改或者删除还在进行中任务的链路"
msgstr ""

#: apps/log_extract/exceptions.py:265
msgid "同名日志提取链路已存在"
msgstr ""

#: apps/log_extract/fileserver.py:166
msgid "获取脚本内容异常({})"
msgstr ""

#: apps/log_extract/handlers/explorer.py:89
#, python-brace-format
msgid ""
"{strategy_name} 策略中的执行人 {operator} 没有JOB的操作权限,无法执行下载操作"
msgstr ""

#: apps/log_extract/handlers/explorer.py:128
msgid "文件预览异常({})"
msgstr ""

#: apps/log_extract/models.py:44
msgid "策略ID"
msgstr ""

#: apps/log_extract/models.py:46 apps/log_extract/serializers.py:278
msgid "策略名称"
msgstr ""

#: apps/log_extract/models.py:47 apps/log_extract/serializers.py:251
msgid "用户ID"
msgstr ""

#: apps/log_extract/models.py:48 apps/log_extract/serializers.py:252
#: apps/log_extract/serializers.py:281
msgid "目标选择类型"
msgstr ""

#: apps/log_extract/models.py:49 apps/log_extract/serializers.py:253
msgid "模块列表"
msgstr ""

#: apps/log_extract/models.py:50 apps/log_extract/serializers.py:254
msgid "目录列表"
msgstr ""

#: apps/log_extract/models.py:51 apps/log_extract/serializers.py:255
msgid "文件类型"
msgstr ""

#: apps/log_extract/models.py:73
msgid "任务记录id"
msgstr ""

#: apps/log_extract/models.py:75 apps/log_extract/serializers.py:55
#: apps/log_extract/serializers.py:329 apps/log_extract/serializers.py:339
msgid "业务机器ip"
msgstr ""

#: apps/log_extract/models.py:81
msgid "当前文件下载状态"
msgstr ""

#: apps/log_extract/models.py:82
msgid "任务过期时间"
msgstr ""

#: apps/log_extract/models.py:83
msgid "流水线ID"
msgstr ""

#: apps/log_extract/models.py:84
msgid "流水线组件ID"
msgstr ""

#: apps/log_extract/models.py:86
msgid "文件分发ID"
msgstr ""

#: apps/log_extract/models.py:89
msgid "上传票据"
msgstr ""

#: apps/log_extract/models.py:90
msgid "上传随机值"
msgstr ""

#: apps/log_extract/models.py:93
msgid "任务上传ID"
msgstr ""

#: apps/log_extract/models.py:94
msgid "云石上传ID"
msgstr ""

#: apps/log_extract/models.py:97
msgid "云石文件路径"
msgstr ""

#: apps/log_extract/models.py:99
msgid "云石任务ID"
msgstr ""

#: apps/log_extract/models.py:100
msgid "云石下载业务ID"
msgstr ""

#: apps/log_extract/models.py:101
msgid "下载票据"
msgstr ""

#: apps/log_extract/models.py:102
msgid "下载随机值"
msgstr ""

#: apps/log_extract/models.py:103 apps/log_extract/serializers.py:235
#: apps/log_extract/serializers.py:344
msgid "任务过程信息"
msgstr ""

#: apps/log_extract/models.py:106 apps/log_extract/serializers.py:109
msgid "预览目录"
msgstr ""

#: apps/log_extract/models.py:107 apps/log_extract/serializers.py:110
msgid "预览地址ip"
msgstr ""

#: apps/log_extract/models.py:108 apps/log_extract/serializers.py:111
msgid "预览日期"
msgstr ""

#: apps/log_extract/models.py:109 apps/log_extract/serializers.py:114
msgid "预览是否搜索子目录"
msgstr ""

#: apps/log_extract/models.py:110
msgid "预览开始日期"
msgstr ""

#: apps/log_extract/models.py:111
msgid "预览结束日期"
msgstr ""

#: apps/log_extract/models.py:113
msgid "额外数据"
msgstr ""

#: apps/log_extract/models.py:114
msgid "cos对象文件名称"
msgstr ""

#: apps/log_extract/models.py:115 apps/log_extract/models.py:190
#: apps/log_extract/serializers.py:408
msgid "链路id"
msgstr ""

#: apps/log_extract/models.py:166
msgid "总耗时"
msgstr ""

#: apps/log_extract/models.py:171
msgid "IP数量"
msgstr ""

#: apps/log_extract/models.py:185
msgid "下载文件统计"
msgstr ""

#: apps/log_extract/models.py:189 apps/log_extract/serializers.py:407
#: apps/log_extract/serializers.py:425
msgid "链路名称"
msgstr ""

#: apps/log_extract/models.py:192 apps/log_extract/serializers.py:427
msgid "执行人"
msgstr ""

#: apps/log_extract/models.py:193 apps/log_extract/serializers.py:428
msgid "执行bk_biz_id"
msgstr ""

#: apps/log_extract/models.py:194 apps/log_extract/serializers.py:429
msgid "腾讯云SecretId"
msgstr ""

#: apps/log_extract/models.py:194 apps/log_extract/models.py:195
#: apps/log_extract/models.py:197 apps/log_extract/models.py:200
msgid "内网链路不需要填写"
msgstr ""

#: apps/log_extract/models.py:195 apps/log_extract/serializers.py:430
msgid "腾讯云SecretKey"
msgstr ""

#: apps/log_extract/models.py:197 apps/log_extract/serializers.py:431
msgid "腾讯云Cos桶名称"
msgstr ""

#: apps/log_extract/models.py:200 apps/log_extract/serializers.py:432
msgid "腾讯云Cos区域"
msgstr ""

#: apps/log_extract/models.py:203 apps/log_extract/serializers.py:411
#: apps/models.py:204
msgid "创建时间"
msgstr ""

#: apps/log_extract/models.py:206 apps/log_extract/models.py:207
msgid ""
"提取链路 (第一次配置链路之后 需要重新部署saas && 暂时只支持linux及安装了cgwin"
"的系统)"
msgstr ""

#: apps/log_extract/models.py:211 apps/log_extract/serializers.py:419
msgid "挂载目录"
msgstr ""

#: apps/log_extract/models.py:212 apps/log_extract/serializers.py:420
msgid "主机云区域id"
msgstr ""

#: apps/log_extract/models.py:213 apps/log_extract/serializers.py:421
msgid "主机ip"
msgstr ""

#: apps/log_extract/models.py:217 apps/log_extract/models.py:218
msgid "链路中转机"
msgstr ""

#: apps/log_extract/serializers.py:56
msgid "业务机器云区域id"
msgstr ""

#: apps/log_extract/serializers.py:61 apps/log_extract/serializers.py:94
msgid "业务机器列表"
msgstr ""

#: apps/log_extract/serializers.py:62
msgid "文件路径"
msgstr ""

#: apps/log_extract/serializers.py:63
msgid "是否搜索子目录"
msgstr ""

#: apps/log_extract/serializers.py:64
msgid "时间跨度"
msgstr ""

#: apps/log_extract/serializers.py:71 apps/log_extract/serializers.py:140
#: apps/log_extract/serializers.py:307
msgid "请指定正确的目录"
msgstr ""

#: apps/log_extract/serializers.py:73
msgid "请指定正确的时间跨度"
msgstr ""

#: apps/log_extract/serializers.py:84
msgid "时间格式不正确"
msgstr ""

#: apps/log_extract/serializers.py:86
msgid "请指定开始和结束时间"
msgstr ""

#: apps/log_extract/serializers.py:99 apps/log_search/serializers.py:250
msgid "搜索关键字"
msgstr ""

#: apps/log_extract/serializers.py:104
msgid "业务机器IP"
msgstr ""

#: apps/log_extract/serializers.py:105
msgid "目标文件路径"
msgstr ""

#: apps/log_extract/serializers.py:107
msgid "过滤参数"
msgstr ""

#: apps/log_extract/serializers.py:112
msgid "预览开始时间"
msgstr ""

#: apps/log_extract/serializers.py:113
msgid "预览结束时间"
msgstr ""

#: apps/log_extract/serializers.py:115
msgid "提取链路id"
msgstr ""

#: apps/log_extract/serializers.py:122
msgid "请指定正确的过滤类型"
msgstr ""

#: apps/log_extract/serializers.py:135
msgid "同时下载的文件数不能超过{}"
msgstr ""

#: apps/log_extract/serializers.py:145
msgid "请指定正确的预览日期模式"
msgstr ""

#: apps/log_extract/serializers.py:157 apps/log_extract/serializers.py:203
msgid "过滤关键词必须为字符串类型"
msgstr ""

#: apps/log_extract/serializers.py:159
msgid "过滤关键词不可为空"
msgstr ""

#: apps/log_extract/serializers.py:161 apps/log_extract/serializers.py:207
msgid "过滤关键字超过长度"
msgstr ""

#: apps/log_extract/serializers.py:164
msgid "过滤关键词请勿包含空格"
msgstr ""

#: apps/log_extract/serializers.py:169
msgid "过滤关键字类型不正确"
msgstr ""

#: apps/log_extract/serializers.py:177
msgid "行数必须为整型"
msgstr ""

#: apps/log_extract/serializers.py:180 apps/log_extract/serializers.py:192
msgid "行数不可为空"
msgstr ""

#: apps/log_extract/serializers.py:183 apps/log_extract/serializers.py:186
msgid "请确认起始行数与终止行数的大小关系"
msgstr ""

#: apps/log_extract/serializers.py:194
msgid "最新行数请输入整数"
msgstr ""

#: apps/log_extract/serializers.py:196
msgid "请保证最新行数大于0"
msgstr ""

#: apps/log_extract/serializers.py:201 apps/log_extract/serializers.py:205
msgid "过滤条件包含空关键词"
msgstr ""

#: apps/log_extract/serializers.py:211 apps/log_extract/serializers.py:215
#: apps/log_extract/serializers.py:233 apps/log_extract/serializers.py:240
#: apps/log_extract/serializers.py:338
msgid "下载任务ID"
msgstr ""

#: apps/log_extract/serializers.py:216
msgid "是否直接返回url"
msgstr ""

#: apps/log_extract/serializers.py:220 apps/log_search/serializers.py:377
msgid "下载任务ID列表"
msgstr ""

#: apps/log_extract/serializers.py:228
msgid "任务列表类型错误,请输入正确的整型数组"
msgstr ""

#: apps/log_extract/serializers.py:234
msgid "当前下载状态"
msgstr ""

#: apps/log_extract/serializers.py:245 apps/log_search/serializers.py:312
msgid "实例名称"
msgstr ""

#: apps/log_extract/serializers.py:246
msgid "对象ID"
msgstr ""

#: apps/log_extract/serializers.py:279 apps/log_search/models.py:651
msgid "用户组ID"
msgstr ""

#: apps/log_extract/serializers.py:280
msgid "授权的业务ID"
msgstr ""

#: apps/log_extract/serializers.py:282
msgid "授权的模板实例列表"
msgstr ""

#: apps/log_extract/serializers.py:283
msgid "授权的目录列表"
msgstr ""

#: apps/log_extract/serializers.py:284
msgid "授权的文件类型"
msgstr ""

#: apps/log_extract/serializers.py:303
msgid "请指定正确的目标选择类型"
msgstr ""

#: apps/log_extract/serializers.py:309
msgid "目录请以 '/' 结尾"
msgstr ""

#: apps/log_extract/serializers.py:314
msgid "文件后缀格式有误"
msgstr ""

#: apps/log_extract/serializers.py:317
msgid "文件后缀不需要使用.开头"
msgstr ""

#: apps/log_extract/serializers.py:341
msgid "任务状态"
msgstr ""

#: apps/log_extract/serializers.py:345
msgid "任务创建者"
msgstr ""

#: apps/log_extract/serializers.py:400
msgid "加密的目标文件名"
msgstr ""

#: apps/log_extract/serializers.py:410 apps/models.py:205
msgid "创建者"
msgstr ""

#: apps/log_extract/serializers.py:434
msgid "中转机列表"
msgstr ""

#: apps/log_measure/exceptions.py:32
msgid "容量管理模块异常"
msgstr ""

#: apps/log_measure/exceptions.py:42
msgid "集群权限异常"
msgstr ""

#: apps/log_measure/exceptions.py:47
msgid "ES连接失败"
msgstr ""

#: apps/log_measure/handlers/metric_collectors/business.py:32
#: apps/log_measure/handlers/metrics.py:271
msgid "活跃业务"
msgstr ""

#: apps/log_measure/handlers/metric_collectors/cluster.py:31
#: apps/log_measure/handlers/metrics.py:425
msgid "集群健康度"
msgstr ""

#: apps/log_measure/handlers/metric_collectors/collect.py:36
#: apps/log_measure/handlers/metrics.py:313
msgid "采集配置"
msgstr ""

#: apps/log_measure/handlers/metric_collectors/es.py:1022
msgid "es 监控信息"
msgstr ""

#: apps/log_measure/handlers/metric_collectors/grafana.py:33
#: apps/log_measure/handlers/metrics.py:538
msgid "Grafana 仪表盘"
msgstr ""

#: apps/log_measure/handlers/metric_collectors/third_party.py:32
#: apps/log_measure/handlers/metrics.py:400 apps/log_search/models.py:140
#: config/default.py:461 config/default.py:530
msgid "第三方ES"
msgstr ""

#: apps/log_measure/handlers/metric_collectors/user.py:38
#: apps/log_measure/handlers/metrics.py:300
msgid "活跃用户"
msgstr ""

#: apps/log_measure/handlers/metric_collectors/user.py:64
msgid "用户检索历史"
msgstr ""

#: apps/log_measure/handlers/metrics.py:338
msgid "采集主机"
msgstr ""

#: apps/log_measure/models.py:28 apps/log_search/models.py:153
#: apps/log_search/models.py:221 apps/log_search/models.py:281
#: apps/log_search/models.py:649 apps/log_search/models.py:683
#: apps/log_search/serializers.py:197 apps/log_search/serializers.py:330
#: apps/log_search/serializers.py:351 apps/log_trace/serializers.py:41
msgid "项目ID"
msgstr ""

#: apps/log_measure/models.py:29 apps/log_search/models.py:279
#: apps/log_search/models.py:560 apps/log_search/models.py:579
#: apps/log_search/models.py:590 apps/log_search/serializers.py:331
msgid "索引集ID"
msgstr ""

#: apps/log_measure/models.py:30
msgid "访问次数"
msgstr ""

#: apps/log_measure/models.py:31
msgid "访问日期"
msgstr ""

#: apps/log_measure/models.py:34 apps/log_measure/models.py:35
msgid "索引集搜索统计"
msgstr ""

#: apps/log_search/constants.py:36
msgid "red"
msgstr ""

#: apps/log_search/constants.py:37
msgid "yellow"
msgstr ""

#: apps/log_search/constants.py:38
msgid "blue"
msgstr ""

#: apps/log_search/constants.py:39
msgid "green"
msgstr ""

#: apps/log_search/constants.py:40
msgid "gray"
msgstr ""

#: apps/log_search/constants.py:136
msgid "必须"
msgstr ""

#: apps/log_search/constants.py:136
msgid "建议"
msgstr ""

#: apps/log_search/constants.py:136
msgid "用户自定义"
msgstr ""

#: apps/log_search/constants.py:147
msgid "字段缺失"
msgstr ""

#: apps/log_search/constants.py:148
msgid "数据类型不匹配"
msgstr ""

#: apps/log_search/constants.py:149 apps/log_search/constants.py:409
msgid "其他"
msgstr ""

#: apps/log_search/constants.py:180
msgid "服务模版"
msgstr ""

#: apps/log_search/constants.py:181
msgid "集群模版"
msgstr ""

#: apps/log_search/constants.py:205
msgid "异常（未知）"
msgstr ""

#: apps/log_search/constants.py:207
msgid "关闭"
msgstr ""

#: apps/log_search/constants.py:208
msgid "Agent未安装"
msgstr ""

#: apps/log_search/constants.py:209
msgid "无数据"
msgstr ""

#: apps/log_search/constants.py:231 apps/log_search/constants.py:399
#: apps/log_trace/constants.py:90 apps/log_trace/handlers/proto/log.py:63
#: apps/log_trace/handlers/proto/log.py:116
#: apps/log_trace/handlers/trace_field_handlers.py:47
#: apps/log_trace/handlers/trace_field_handlers.py:91
#: apps/log_trace/handlers/trace_field_handlers.py:138
#: apps/log_trace/handlers/trace_field_handlers.py:156
#: apps/log_trace/handlers/trace_field_handlers.py:187
msgid "服务"
msgstr ""

#: apps/log_search/constants.py:255
msgid "分隔符列表"
msgstr ""

#: apps/log_search/constants.py:256
msgid "编码格式"
msgstr ""

#: apps/log_search/constants.py:257
msgid "数据保留时间"
msgstr ""

#: apps/log_search/constants.py:258
msgid "字段提取方式"
msgstr ""

#: apps/log_search/constants.py:259
msgid "字段类型"
msgstr ""

#: apps/log_search/constants.py:261
msgid "内置字段"
msgstr ""

#: apps/log_search/constants.py:262 apps/log_search/models.py:306
msgid "时间字段类型"
msgstr ""

#: apps/log_search/constants.py:263 apps/log_search/models.py:307
msgid "时间字段单位"
msgstr ""

#: apps/log_search/constants.py:273
msgid "行日志文件"
msgstr ""

#: apps/log_search/constants.py:274
msgid "段日志文件"
msgstr ""

#: apps/log_search/constants.py:275
msgid "win event日志"
msgstr ""

#: apps/log_search/constants.py:296
msgid "JSON"
msgstr ""

#: apps/log_search/constants.py:306
msgid "win event"
msgstr ""

#: apps/log_search/constants.py:395
msgid "操作系统"
msgstr ""

#: apps/log_search/constants.py:400
msgid "服务模块"
msgstr ""

#: apps/log_search/constants.py:406
msgid "业务应用"
msgstr ""

#: apps/log_search/constants.py:469
msgid "包含"
msgstr ""

#: apps/log_search/constants.py:470
msgid "不包含"
msgstr ""

#: apps/log_search/constants.py:483
msgid "字符串"
msgstr ""

#: apps/log_search/constants.py:500
msgid "竖线(|)"
msgstr ""

#: apps/log_search/constants.py:501
msgid "逗号(,)"
msgstr ""

#: apps/log_search/constants.py:502
msgid "反引号(`)"
msgstr ""

#: apps/log_search/constants.py:503
msgid "空格"
msgstr ""

#: apps/log_search/constants.py:504
msgid "分号(;)"
msgstr ""

#: apps/log_search/constants.py:531
msgid "1天"
msgstr ""

#: apps/log_search/constants.py:532
msgid "3天"
msgstr ""

#: apps/log_search/constants.py:533
msgid "7天"
msgstr ""

#: apps/log_search/constants.py:534
msgid "14天"
msgstr ""

#: apps/log_search/constants.py:535
msgid "30天"
msgstr ""

#: apps/log_search/constants.py:548
msgid "date"
msgstr ""

#: apps/log_search/constants.py:549
msgid "long"
msgstr ""

#: apps/log_search/constants.py:562
msgid "second"
msgstr ""

#: apps/log_search/constants.py:562
msgid "millisecond"
msgstr ""

#: apps/log_search/constants.py:562
msgid "microsecond"
msgstr ""

#: apps/log_search/exceptions.py:35
msgid "参数校验异常：项目ID不存在"
msgstr ""

#: apps/log_search/exceptions.py:43
msgid "管理模块异常"
msgstr ""

#: apps/log_search/exceptions.py:53
msgid "接入场景异常"
msgstr ""

#: apps/log_search/exceptions.py:58
#, python-brace-format
msgid "暂不支持\"{scenario_id}\"场景的操作"
msgstr ""

#: apps/log_search/exceptions.py:63
#, python-brace-format
msgid "探测ES连通性失败,失败原因：\"{es_fail_reason}\""
msgstr ""

#: apps/log_search/exceptions.py:73
#, python-brace-format
msgid "EsClient查询index失败,失败原因:\"{es_fail_reason}\""
msgstr ""

#: apps/log_search/exceptions.py:81
msgid "数据源模块异常"
msgstr ""

#: apps/log_search/exceptions.py:86
#, python-brace-format
msgid "该项目下已存在名称为\"{source_name}\"的数据源"
msgstr ""

#: apps/log_search/exceptions.py:91
msgid "数据源不存在"
msgstr ""

#: apps/log_search/exceptions.py:96
msgid "此数据源不允许编辑"
msgstr ""

#: apps/log_search/exceptions.py:101
msgid "ES服务器连接异常"
msgstr ""

#: apps/log_search/exceptions.py:106
msgid "此数据源已有关联的索引集，无法直接删除"
msgstr ""

#: apps/log_search/exceptions.py:116
msgid "索引集模块异常"
msgstr ""

#: apps/log_search/exceptions.py:121
msgid "索引集不存在"
msgstr ""

#: apps/log_search/exceptions.py:126
#, python-brace-format
msgid "索引\"{result_table_id}\"在数据平台中不存在"
msgstr ""

#: apps/log_search/exceptions.py:131
#, python-brace-format
msgid "该项目下已存在名称为\"{index_set_name}\"的数据集"
msgstr ""

#: apps/log_search/exceptions.py:136
#, python-brace-format
msgid "索引\"{result_table_id}\"在此ES中不存在"
msgstr ""

#: apps/log_search/exceptions.py:141
#, python-brace-format
msgid "该索引集下已存在\"{result_table_id}\"结果表"
msgstr ""

#: apps/log_search/exceptions.py:146
msgid "索引字段不一致，无法添加索引到同一个索引集中"
msgstr ""

#: apps/log_search/exceptions.py:151
msgid "索引已存在，请勿添加相同索引"
msgstr ""

#: apps/log_search/exceptions.py:156
msgid "索引集不支持跨业务"
msgstr ""

#: apps/log_search/exceptions.py:161
msgid "获取结果表信息失败"
msgstr ""

#: apps/log_search/exceptions.py:166
msgid "索引集不支持跨集群"
msgstr ""

#: apps/log_search/exceptions.py:171
msgid "索引列表数据异常"
msgstr ""

#: apps/log_search/exceptions.py:176
msgid "索引列表不满足Trace要求"
msgstr ""

#: apps/log_search/exceptions.py:181
msgid "项目ID不存在无法搜索TRACE类型索引集"
msgstr ""

#: apps/log_search/exceptions.py:186
#, python-brace-format
msgid "索引字段{field_type}类型不一致，无法添加索引到同一个索引集中"
msgstr ""

#: apps/log_search/exceptions.py:191
msgid "索引缺少时间字段，无法添加索引到同一个索引集中"
msgstr ""

#: apps/log_search/exceptions.py:196
msgid "索引时间字段不同，无法添加索引到同一个索引集中"
msgstr ""

#: apps/log_search/exceptions.py:201
msgid "索引时间字段类型不同，无法添加索引到同一个索引集中"
msgstr ""

#: apps/log_search/exceptions.py:206
#, python-brace-format
msgid "索引{result_table_id} mapping信息查询结果为空"
msgstr ""

#: apps/log_search/exceptions.py:211
msgid "您没有此索引集的编辑权限"
msgstr ""

#: apps/log_search/exceptions.py:216
msgid "索引集不能为空集"
msgstr ""

#: apps/log_search/exceptions.py:221
msgid "索引集中的索引字段不能有冲突"
msgstr ""

#: apps/log_search/exceptions.py:231
msgid "检索模块异常"
msgstr ""

#: apps/log_search/exceptions.py:241
#, python-brace-format
msgid "找不到索引集\"{index_set_id}\"的时间字段信息，无法进行检索"
msgstr ""

#: apps/log_search/exceptions.py:246
msgid "将时间字段转换成handler接口可用格式失败"
msgstr ""

#: apps/log_search/exceptions.py:251
msgid "参数中没有keyword"
msgstr ""

#: apps/log_search/exceptions.py:256
msgid "参数中没有开始指针"
msgstr ""

#: apps/log_search/exceptions.py:261
msgid "场景选择错误"
msgstr ""

#: apps/log_search/exceptions.py:266
msgid "查询上下文需要gseindex相关信息"
msgstr ""

#: apps/log_search/exceptions.py:271
msgid "链接到ES数据源失败"
msgstr ""

#: apps/log_search/exceptions.py:276
msgid "添加用户index字段时缺少相关参数"
msgstr ""

#: apps/log_search/exceptions.py:281
#, python-brace-format
msgid "查询ES中索引下的fields字段失败,失败原因{fail_reason}"
msgstr ""

#: apps/log_search/exceptions.py:296
msgid "不需要输出"
msgstr ""

#: apps/log_search/exceptions.py:301
#, python-brace-format
msgid "search dict empty错误{search_dict}"
msgstr ""

#: apps/log_search/exceptions.py:306
#, python-brace-format
msgid "该字段{sort_item}不支持排序"
msgstr ""

#: apps/log_search/exceptions.py:311
#, python-brace-format
msgid "拉取schema错误{index}"
msgstr ""

#: apps/log_search/exceptions.py:316
msgid "Trace查询time field不存在"
msgstr ""

#: apps/log_search/exceptions.py:321
#, python-brace-format
msgid "超出最大查询数量：{size}"
msgstr ""

#: apps/log_search/exceptions.py:326
msgid "未知的时间字段类型"
msgstr ""

#: apps/log_search/exceptions.py:331
msgid "未知的时间字段/时间字段类型/时间字段单位"
msgstr ""

#: apps/log_search/exceptions.py:336
#, python-brace-format
msgid "用户无结果表 {result_tables} 的管理权限，无法添加到索引集中"
msgstr ""

#: apps/log_search/exceptions.py:341
msgid "此索引没有找到时间字段类型"
msgstr ""

#: apps/log_search/exceptions.py:346
msgid "收藏查询不存在"
msgstr ""

#: apps/log_search/exceptions.py:351
#, python-brace-format
msgid "索引集【{index_set_id}】聚合查询异常：{err}"
msgstr ""

#: apps/log_search/exceptions.py:361
#, python-brace-format
msgid "对应索引集{index_set_id}缺少异步导出必备fields"
msgstr ""

#: apps/log_search/exceptions.py:366
#, python-brace-format
msgid "超过异步导出最大条数限制{max_async_export_count}"
msgstr ""

#: apps/log_search/exceptions.py:371
#, python-brace-format
msgid "无法找到{template_name}{language}相关模板"
msgstr ""

#: apps/log_search/exceptions.py:381
msgid "请升级blueapps至最新版本"
msgstr ""

#: apps/log_search/exceptions.py:386
msgid "获取JWT信息异常"
msgstr ""

#: apps/log_search/exceptions.py:391
msgid "JWT校验失败"
msgstr ""

#: apps/log_search/exceptions.py:396
msgid "配置中menu对象异常"
msgstr ""

#: apps/log_search/handlers/biz.py:477
msgid "无法识别节点"
msgstr ""

#: apps/log_search/handlers/index_set.py:171 apps/log_search/models.py:553
msgid "审批中"
msgstr ""

#: apps/log_search/handlers/search/mapping_handlers.py:632
msgid "必须path或者logfile字段"
msgstr ""

#: apps/log_search/handlers/search/mapping_handlers.py:637
msgid "必须_iteration_idx字段"
msgstr ""

#: apps/log_search/handlers/search/mapping_handlers.py:643
msgid "必须ip或者container_id字段"
msgstr ""

#: apps/log_search/handlers/search/mapping_handlers.py:648
msgid "必须serverIp字段"
msgstr ""

#: apps/log_search/handlers/search/mapping_handlers.py:651
msgid "必须path字段"
msgstr ""

#: apps/log_search/handlers/search/mapping_handlers.py:654
msgid "必须iterationIndex或者_iteration_idx字段"
msgstr ""

#: apps/log_search/handlers/search/mapping_handlers.py:656
msgid "必须gseindex或者gseIndex字段"
msgstr ""

#: apps/log_search/handlers/search/mapping_handlers.py:710
msgid "【异步导出功能尚未开放】"
msgstr ""

#: apps/log_search/handlers/search/mapping_handlers.py:737
#, python-brace-format
msgid "【异步导出缺少必备字段: {async_fields} or {async_container_fields}】"
msgstr ""

#: apps/log_search/handlers/search/mapping_handlers.py:740
#, python-brace-format
msgid "【异步导出缺少必备字段: {async_fields}】"
msgstr ""

#: apps/log_search/migrations/0002_bklog_initial.py:38
msgid "ES"
msgstr ""

#: apps/log_search/migrations/0002_bklog_initial.py:39
msgid "日志文件"
msgstr ""

#: apps/log_search/migrations/0002_bklog_initial.py:59
msgid "阈值监控"
msgstr ""

#: apps/log_search/models.py:77
msgid "配置标识"
msgstr ""

#: apps/log_search/models.py:78
msgid "具体配置"
msgstr ""

#: apps/log_search/models.py:119 apps/log_search/models.py:120
msgid "00_全局配置"
msgstr ""

#: apps/log_search/models.py:138 config/default.py:518
msgid "采集接入"
msgstr ""

#: apps/log_search/models.py:154
msgid "项目名称"
msgstr ""

#: apps/log_search/models.py:159
msgid "是否可以使用ip快选"
msgstr ""

#: apps/log_search/models.py:160
msgid "是否为 CMDB V3 业务"
msgstr ""

#: apps/log_search/models.py:161
msgid "是否混合使用CMDB V3 业务"
msgstr ""

#: apps/log_search/models.py:162
msgid "功能白名单"
msgstr ""

#: apps/log_search/models.py:209
msgid "项目列表"
msgstr ""

#: apps/log_search/models.py:210
msgid "02_项目列表"
msgstr ""

#: apps/log_search/models.py:218 apps/log_search/models.py:287
#: apps/log_search/serializers.py:77 apps/log_search/serializers.py:93
msgid "数据源ID"
msgstr ""

#: apps/log_search/models.py:220 apps/log_search/models.py:285
msgid "接入场景标识"
msgstr ""

#: apps/log_search/models.py:222
msgid "属性"
msgstr ""

#: apps/log_search/models.py:223 apps/log_search/models.py:288
msgid "顺序"
msgstr ""

#: apps/log_search/models.py:224
msgid "是否可以编辑"
msgstr ""

#: apps/log_search/models.py:243
#, python-brace-format
msgid "此项目[{self.project_id}]下已存在"
msgstr ""

#: apps/log_search/models.py:262
msgid "暂不支持除ES自定义场景意外的其它场景"
msgstr ""

#: apps/log_search/models.py:266
msgid "ES集群配置"
msgstr ""

#: apps/log_search/models.py:267
msgid "03_ES集群配置"
msgstr ""

#: apps/log_search/models.py:280
msgid "索引集名称"
msgstr ""

#: apps/log_search/models.py:283
msgid "绑定的数据平台项目ID"
msgstr ""

#: apps/log_search/models.py:284
msgid "绑定Transfer采集ID"
msgstr ""

#: apps/log_search/models.py:286 apps/log_search/serializers.py:114
msgid "存储集群ID"
msgstr ""

#: apps/log_search/models.py:293
msgid "是否通过"
msgstr ""

#: apps/log_search/models.py:294
msgid "预查询描述"
msgstr ""

#: apps/log_search/models.py:297
msgid "字段快照"
msgstr ""

#: apps/log_search/models.py:300
msgid "是否trace"
msgstr ""

#: apps/log_search/models.py:302
msgid "来源系统"
msgstr ""

#: apps/log_search/models.py:305 apps/log_search/models.py:564
msgid "时间字段"
msgstr ""

#: apps/log_search/models.py:308
msgid "标签id记录"
msgstr ""

#: apps/log_search/models.py:537
msgid "索引集配置"
msgstr ""

#: apps/log_search/models.py:538
msgid "21_索引集配置"
msgstr ""

#: apps/log_search/models.py:555
msgid "拒绝"
msgstr ""

#: apps/log_search/models.py:556
msgid "异常"
msgstr ""

#: apps/log_search/models.py:559
msgid "索引ID"
msgstr ""

#: apps/log_search/models.py:562
msgid "结果表"
msgstr ""

#: apps/log_search/models.py:563
msgid "结果表名称"
msgstr ""

#: apps/log_search/models.py:565
msgid "审核状态"
msgstr ""

#: apps/log_search/models.py:574
msgid "索引集数据"
msgstr ""

#: apps/log_search/models.py:575
msgid "22_索引集详情"
msgstr ""

#: apps/log_search/models.py:581 apps/log_search/serializers.py:211
msgid "排序规则"
msgstr ""

#: apps/log_search/models.py:582
msgid "应用范围"
msgstr ""

#: apps/log_search/models.py:585
msgid "索引集自定义显示"
msgstr ""

#: apps/log_search/models.py:586
msgid "31_搜索-索引集自定义显示"
msgstr ""

#: apps/log_search/models.py:591
msgid "检索条件"
msgstr ""

#: apps/log_search/models.py:592
msgid "检索类型"
msgstr ""

#: apps/log_search/models.py:593
msgid "查询耗时"
msgstr ""

#: apps/log_search/models.py:594
msgid "排序"
msgstr ""

#: apps/log_search/models.py:597
msgid "索引集用户检索记录"
msgstr ""

#: apps/log_search/models.py:598
msgid "32_搜索-索引集用户检索记录"
msgstr ""

#: apps/log_search/models.py:621
msgid "用户组"
msgstr ""

#: apps/log_search/models.py:622
msgid "资源"
msgstr ""

#: apps/log_search/models.py:635
msgid "待处理"
msgstr ""

#: apps/log_search/models.py:636
msgid "同步完成"
msgstr ""

#: apps/log_search/models.py:637
msgid "同步失败"
msgstr ""

#: apps/log_search/models.py:650
msgid "变更类型"
msgstr ""

#: apps/log_search/models.py:652
msgid "资源类型"
msgstr ""

#: apps/log_search/models.py:653
msgid "范围"
msgstr ""

#: apps/log_search/models.py:654
msgid "同步状态"
msgstr ""

#: apps/log_search/models.py:655
msgid "同步时间"
msgstr ""

#: apps/log_search/models.py:675
msgid "资源变更任务"
msgstr ""

#: apps/log_search/models.py:676
msgid "23_资源变更任务"
msgstr ""

#: apps/log_search/models.py:682
msgid "用户检索历史记录ID"
msgstr ""

#: apps/log_search/models.py:684 apps/log_search/serializers.py:332
msgid "收藏描述"
msgstr ""

#: apps/log_search/models.py:687 apps/log_search/models.py:697
msgid "检索收藏记录"
msgstr ""

#: apps/log_search/models.py:688 apps/log_search/models.py:698
msgid "33_搜索-检索收藏记录"
msgstr ""

#: apps/log_search/models.py:692
msgid "id"
msgstr ""

#: apps/log_search/models.py:694
msgid "用户name"
msgstr ""

#: apps/log_search/models.py:722
msgid "标签id"
msgstr ""

#: apps/log_search/models.py:723
msgid "标签名称"
msgstr ""

#: apps/log_search/models.py:724
msgid "配色"
msgstr ""

#: apps/log_search/models.py:727 apps/log_search/models.py:728
msgid "标签表"
msgstr ""

#: apps/log_search/models.py:746
msgid "检索请求参数"
msgstr ""

#: apps/log_search/models.py:747
msgid "异步导出排序字段"
msgstr ""

#: apps/log_search/models.py:748 apps/log_search/serializers.py:56
#: apps/log_search/serializers.py:76 apps/log_search/serializers.py:92
#: apps/log_search/serializers.py:113
msgid "接入场景"
msgstr ""

#: apps/log_search/models.py:750
msgid "异步导出结果"
msgstr ""

#: apps/log_search/models.py:751
msgid "异步导出异常原因"
msgstr ""

#: apps/log_search/models.py:752
msgid "文件名"
msgstr ""

#: apps/log_search/models.py:753
msgid "文件大小"
msgstr ""

#: apps/log_search/models.py:754
msgid "下载地址"
msgstr ""

#: apps/log_search/models.py:755
msgid "是否被清理"
msgstr ""

#: apps/log_search/models.py:758
msgid "异步导出任务"
msgstr ""

#: apps/log_search/models.py:759
msgid "42_异步导出任务"
msgstr ""

#: apps/log_search/models.py:768
msgid "模板路径"
msgstr ""

#: apps/log_search/models.py:769
msgid "语言级别"
msgstr ""

#: apps/log_search/models.py:798
msgid "邮件模板"
msgstr ""

#: apps/log_search/models.py:799
msgid "43_邮件模板"
msgstr ""

#: apps/log_search/serializers.py:46
msgid "分页大小"
msgstr ""

#: apps/log_search/serializers.py:59
msgid "索引"
msgstr ""

#: apps/log_search/serializers.py:66
msgid "业务ID不能为空"
msgstr ""

#: apps/log_search/serializers.py:69 apps/log_search/serializers.py:85
#: apps/log_search/serializers.py:100 apps/log_search/serializers.py:124
msgid "数据源ID不能为空"
msgstr ""

#: apps/log_search/serializers.py:75
msgid "索引列表"
msgstr ""

#: apps/log_search/serializers.py:87
msgid "indices不能为空"
msgstr ""

#: apps/log_search/serializers.py:115 apps/log_search/serializers.py:116
msgid "源索引"
msgstr ""

#: apps/log_search/serializers.py:117
msgid "待追加的索引"
msgstr ""

#: apps/log_search/serializers.py:131
msgid "源索引时间字段不能为空"
msgstr ""

#: apps/log_search/serializers.py:133
msgid "源索引时间字段类型不能为空"
msgstr ""

#: apps/log_search/serializers.py:137
msgid "待追加索引时间字段不能为空"
msgstr ""

#: apps/log_search/serializers.py:139
msgid "待追加索引时间字段类型不能为空"
msgstr ""

#: apps/log_search/serializers.py:180
msgid "最大只支持查询7天数据"
msgstr ""

#: apps/log_search/serializers.py:204 apps/log_search/serializers.py:358
#: apps/log_trace/serializers.py:45
msgid "请输入业务ID"
msgstr ""

#: apps/log_search/serializers.py:216
msgid "sort_list参数格式有误"
msgstr ""

#: apps/log_search/serializers.py:219
msgid "排序规则只支持升序asc或降序desc"
msgstr ""

#: apps/log_search/serializers.py:251
msgid "时间范围"
msgstr ""

#: apps/log_search/serializers.py:252
msgid "起始时间"
msgstr ""

#: apps/log_search/serializers.py:254
msgid "检索模块ip等信息"
msgstr ""

#: apps/log_search/serializers.py:255
msgid "搜索条件"
msgstr ""

#: apps/log_search/serializers.py:256
msgid "检索开始 offset"
msgstr ""

#: apps/log_search/serializers.py:257
msgid "检索结果大小"
msgstr ""

#: apps/log_search/serializers.py:258
msgid "匹配规则"
msgstr ""

#: apps/log_search/serializers.py:274
msgid "ES HOST"
msgstr ""

#: apps/log_search/serializers.py:275
msgid "ES 端口"
msgstr ""

#: apps/log_search/serializers.py:276
msgid "ES 用户"
msgstr ""

#: apps/log_search/serializers.py:277
msgid "ES 密码"
msgstr ""

#: apps/log_search/serializers.py:285
msgid "主机IP"
msgstr ""

#: apps/log_search/serializers.py:286
msgid "云区域ID"
msgstr ""

#: apps/log_search/serializers.py:311
msgid "实例id"
msgstr ""

#: apps/log_search/serializers.py:313
msgid "类型id"
msgstr ""

#: apps/log_search/serializers.py:339
msgid "索引集ID不能为空"
msgstr ""

#: apps/log_search/serializers.py:341
msgid "项目id不能为空"
msgstr ""

#: apps/log_search/serializers.py:368
msgid "集群id"
msgstr ""

#: apps/log_search/serializers.py:369
msgid "容器id"
msgstr ""

#: apps/log_search/serializers.py:373 apps/log_search/serializers.py:378
msgid "模版类型"
msgstr ""

#: apps/log_search/serializers.py:386
msgid "类型错误,请输入正确的整型数组"
msgstr ""

#: apps/log_search/tasks/async_export.py:267
#, python-brace-format
msgid "【{platform}】{index_set_name} 检索导出"
msgstr ""

#: apps/log_search/tasks/async_export.py:268
#, python-brace-format
msgid "【{platform}】{index_set_name} 检索导出失败"
msgstr ""

#: apps/log_search/views/index_set_views.py:111
msgid "集群ID不能为空"
msgstr ""

#: apps/log_search/views/index_set_views.py:119
#, python-brace-format
msgid "业务({bk_biz_id})对应的项目信息不存在"
msgstr ""

#: apps/log_search/views/index_set_views.py:122
msgid "参数 bk_biz_id 和 project_id 请至少提供一项"
msgstr ""

#: apps/log_search/views/meta_views.py:379
msgid "请选择语言"
msgstr ""

#: apps/log_search/views/meta_views.py:428
msgid "project_id不能为空"
msgstr ""

#: apps/log_search/views/search_views.py:491
#, python-brace-format
msgid "任务提交成功，系统处理后将通过{notify_type_name}通知，请留意！"
msgstr ""

#: apps/log_search/views/search_views.py:557
#: apps/log_search/views/search_views.py:620
msgid "scope取值范围：default、search_context"
msgstr ""

#: apps/log_search/views/search_views.py:656
msgid "is"
msgstr ""

#: apps/log_search/views/search_views.py:657
msgid "is one of"
msgstr ""

#: apps/log_search/views/search_views.py:658
msgid "is not"
msgstr ""

#: apps/log_search/views/search_views.py:659
msgid "is not one of"
msgstr ""

#: apps/log_search/views/search_views.py:660
msgid "大于"
msgstr ""

#: apps/log_search/views/search_views.py:661
msgid "大于等于"
msgstr ""

#: apps/log_search/views/search_views.py:662
msgid "小于"
msgstr ""

#: apps/log_search/views/search_views.py:663
msgid "小于等于"
msgstr ""

#: apps/log_search/views/search_views.py:664
msgid "exists"
msgstr ""

#: apps/log_search/views/search_views.py:664
msgid "确认字段已存在"
msgstr ""

#: apps/log_search/views/search_views.py:665
msgid "does not exists"
msgstr ""

#: apps/log_search/views/search_views.py:665
msgid "确认字段不存在"
msgstr ""

#: apps/log_trace/constants.py:29
msgid "日志平台协议"
msgstr ""

#: apps/log_trace/constants.py:30
msgid "opentelemetry协议"
msgstr ""

#: apps/log_trace/constants.py:42
msgid "关联"
msgstr ""

#: apps/log_trace/constants.py:42
msgid "取消关联"
msgstr ""

#: apps/log_trace/constants.py:50
msgid "traceID"
msgstr ""

#: apps/log_trace/constants.py:57
msgid "spanID"
msgstr ""

#: apps/log_trace/constants.py:64
msgid "SPAN"
msgstr ""

#: apps/log_trace/constants.py:78
#: apps/log_trace/handlers/trace_field_handlers.py:45
msgid "耗时"
msgstr ""

#: apps/log_trace/constants.py:89 apps/log_trace/handlers/proto/log.py:56
#: apps/log_trace/handlers/proto/log.py:108
#: apps/log_trace/handlers/trace_field_handlers.py:46
#: apps/log_trace/handlers/trace_field_handlers.py:89
#: apps/log_trace/handlers/trace_field_handlers.py:130
msgid "场景"
msgstr ""

#: apps/log_trace/constants.py:91 apps/log_trace/handlers/proto/log.py:86
#: apps/log_trace/handlers/proto/log.py:100
#: apps/log_trace/handlers/proto/otlp.py:79
#: apps/log_trace/handlers/trace_field_handlers.py:48
#: apps/log_trace/handlers/trace_field_handlers.py:113
#: apps/log_trace/handlers/trace_field_handlers.py:122
msgid "返回码"
msgstr ""

#: apps/log_trace/constants.py:100
#: apps/log_trace/handlers/trace_field_handlers.py:50
msgid "日志"
msgstr ""

#: apps/log_trace/constants.py:114
msgid "数据时间"
msgstr ""

#: apps/log_trace/constants.py:133
msgid "平均聚合"
msgstr ""

#: apps/log_trace/constants.py:134
msgid "最大聚合"
msgstr ""

#: apps/log_trace/constants.py:135
msgid "最小聚合"
msgstr ""

#: apps/log_trace/constants.py:136
msgid "总和"
msgstr ""

#: apps/log_trace/constants.py:137
msgid "基数聚合"
msgstr ""

#: apps/log_trace/constants.py:138
msgid "统计汇总"
msgstr ""

#: apps/log_trace/exceptions.py:35
msgid "trace_id不存在"
msgstr ""

#: apps/log_trace/exceptions.py:40
msgid "trace日志没有找到根节点"
msgstr ""

#: apps/log_trace/exceptions.py:45
msgid "协议未支持"
msgstr ""

#: apps/log_trace/handlers/proto/log.py:34
msgid "成功"
msgstr ""

#: apps/log_trace/handlers/proto/log.py:60
#: apps/log_trace/handlers/proto/log.py:67
#: apps/log_trace/handlers/proto/log.py:74
#: apps/log_trace/handlers/proto/otlp.py:60
#: apps/log_trace/handlers/proto/otlp.py:67
#: apps/log_trace/handlers/proto/otlp.py:74
#: apps/log_trace/handlers/trace_field_handlers.py:89
#: apps/log_trace/handlers/trace_field_handlers.py:95
#: apps/log_trace/handlers/trace_field_handlers.py:102
#: apps/log_trace/handlers/trace_field_handlers.py:160
#: apps/log_trace/handlers/trace_field_handlers.py:167
msgid "请选择"
msgstr ""

#: apps/log_trace/handlers/proto/log.py:70
#: apps/log_trace/handlers/trace_field_handlers.py:98
#: apps/log_trace/handlers/trace_field_handlers.py:163
msgid "操作名"
msgstr ""

#: apps/log_trace/handlers/proto/log.py:79
#: apps/log_trace/handlers/trace_field_handlers.py:107
#: apps/log_trace/handlers/trace_field_handlers.py:172
msgid "耗时min_max"
msgstr ""

#: apps/log_trace/handlers/proto/log.py:96
#: apps/log_trace/handlers/trace_field_handlers.py:118
#: apps/log_trace/handlers/trace_field_handlers.py:183
msgid "曲线图"
msgstr ""

#: apps/log_trace/handlers/proto/log.py:104
#: apps/log_trace/handlers/proto/log.py:112
#: apps/log_trace/handlers/trace_field_handlers.py:126
#: apps/log_trace/handlers/trace_field_handlers.py:134
msgid "耗时图"
msgstr ""

#: apps/log_trace/handlers/proto/log.py:120
#: apps/log_trace/handlers/proto/otlp.py:88
#: apps/log_trace/handlers/trace_field_handlers.py:142
#: apps/log_trace/handlers/trace_field_handlers.py:191
msgid "调用关系图"
msgstr ""

#: apps/log_trace/handlers/proto/log.py:126
#: apps/log_trace/handlers/proto/otlp.py:94
#: apps/log_trace/handlers/trace_field_handlers.py:148
#: apps/log_trace/handlers/trace_field_handlers.py:197
msgid "operationName调用关系"
msgstr ""

#: apps/log_trace/handlers/proto/otlp.py:56
msgid "名称"
msgstr ""

#: apps/log_trace/handlers/proto/otlp.py:70
msgid "trace状态"
msgstr ""

#: apps/log_trace/serializers.py:134
msgid "metric_field字段不能为空"
msgstr ""

#: apps/log_trace/views/trace_views.py:537
#: apps/log_trace/views/trace_views.py:566
msgid "scope取值范围：trace、trace_detail、trace_detail_log"
msgstr ""

#: apps/middlewares.py:131
msgid "S-mart应用仅支持正式环境部署！"
msgstr ""

#: apps/models.py:206
msgid "更新时间"
msgstr ""

#: apps/models.py:207
msgid "修改者"
msgstr ""

#: apps/models.py:262
msgid "删除时间"
msgstr ""

#: apps/models.py:263
msgid "删除者"
msgstr ""

#: apps/utils/cos.py:36
msgid "请设置腾讯云cos SecretId"
msgstr ""

#: apps/utils/cos.py:37
msgid "请设置腾讯云cos SecretKey"
msgstr ""

#: apps/utils/cos.py:38
msgid "请设置腾讯云cos 区域"
msgstr ""

#: apps/utils/cos.py:39
msgid "请设置腾讯云cos 桶名称"
msgstr ""

#: apps/utils/drf.py:42
msgid "参数校验失败:\n"
msgstr ""

#: apps/utils/drf.py:76
#, python-brace-format
msgid ""
"\n"
"{prefix}第{index}项:"
msgstr ""

#: apps/utils/drf.py:109
msgid "参数校验失败，详情请查看返回的errors"
msgstr ""

#: bk_monitor/handler/monitor.py:86
msgid "数据源名称不能为空"
msgstr ""

#: bk_monitor/handler/monitor.py:115
#, python-brace-format
msgid ""
"data_id已创建却无法获取相关信息， 建议联系管理员处理 data_name -> {data_name}"
msgstr ""

#: bk_monitor/handler/monitor.py:117
msgid "data_id已创建却无法获取相关信息， 建议联系管理员处理"
msgstr ""

#: bk_monitor/handler/monitor.py:160
#, python-brace-format
msgid "f{key} data_name初始化异常，请检查"
msgstr ""

#: bk_monitor/handler/monitor.py:202
#, python-brace-format
msgid "{val} data对应数据源为空，请检查数据源"
msgstr ""

#: bk_monitor/handler/monitor.py:206
#, python-brace-format
msgid "{val} 数据源采集的数据为空"
msgstr ""

#: bk_monitor/models.py:9
msgid "监控数据源id"
msgstr ""

#: bk_monitor/models.py:11
msgid "指定业务id"
msgstr ""

#: bk_monitor/models.py:13
msgid "数据上报token"
msgstr ""

#: bk_monitor/models.py:14
msgid "数据源是否enable"
msgstr ""

#: bk_monitor/models.py:17 bk_monitor/models.py:18
msgid "运营数据上报配置"
msgstr ""

#: bk_monitor/utils/query.py:52
#, python-brace-format
msgid "{self.data_name} data_name 不存在， 请先初始化"
msgstr ""

#: config/default.py:417
msgid "检索"
msgstr ""

#: config/default.py:418
msgid "调用链"
msgstr ""

#: config/default.py:419 config/default.py:493
msgid "日志提取"
msgstr ""

#: config/default.py:420
msgid "监控策略"
msgstr ""

#: config/default.py:423
msgid "仪表盘"
msgstr ""

#: config/default.py:427
msgid "新建仪表盘"
msgstr ""

#: config/default.py:428
msgid "新建目录"
msgstr ""

#: config/default.py:429
msgid "导入仪表盘"
msgstr ""

#: config/default.py:434 templates/admin/base_site.html:4
#: templates/admin/base_site.html:7
msgid "管理"
msgstr ""

#: config/default.py:440
msgid "日志接入"
msgstr ""

#: config/default.py:443
msgid "接入"
msgstr ""

#: config/default.py:447
msgid "日志采集"
msgstr ""

#: config/default.py:454 config/default.py:525
msgid "计算平台"
msgstr ""

#: config/default.py:466
msgid "自定义接入"
msgstr ""

#: config/default.py:471
msgid "日志清洗"
msgstr ""

#: config/default.py:474
msgid "清洗"
msgstr ""

#: config/default.py:478
msgid "清洗列表"
msgstr ""

#: config/default.py:495
msgid "提取"
msgstr ""

#: config/default.py:498
msgid "日志提取配置"
msgstr ""

#: config/default.py:499
msgid "提取链路管理"
msgstr ""

#: config/default.py:504 config/default.py:507
msgid "日志归档"
msgstr ""

#: config/default.py:511
msgid "全链路追踪"
msgstr ""

#: config/default.py:531
msgid "SDK接入"
msgstr ""

#: config/default.py:536
msgid "ES集群"
msgstr ""

#: config/default.py:540
msgid "集群管理"
msgstr ""

#: config/default.py:544 config/default.py:547
msgid "设置"
msgstr ""

#: config/default.py:549
msgid "采集链路管理"
msgstr ""

#: templates/admin/login.html:6
msgid "您暂时不能访问该站点的后台管理，这是以下原因造成的："
msgstr ""

#: templates/admin/login.html:9
msgid "你还没登录，请重新刷新页面！"
msgstr ""

#: templates/admin/login.html:12
msgid "未激活！"
msgstr ""

#: templates/admin/login.html:14
msgid "没有管理员权限，请联系管理员！"
msgstr ""

#: templates/admin/login.html:18
msgid "如有需要，请联系管理员或开发者为您解决上述问题。"
msgstr ""

#: version_log/config.py:31
msgid "版本日志"
msgstr ""

#: version_log/models.py:43
msgid "访问版本"
msgstr ""

#: version_log/models.py:48
msgid "版本日志访问记录"
msgstr ""

#: version_log/templates/version_log/version_logs_page.html:27
msgid "返回"
msgstr ""

#: version_log/views.py:56
msgid "访问出错，请联系管理员。"
msgstr ""

#: version_log/views.py:57
msgid "日志列表获取成功"
msgstr ""

#: version_log/views.py:67
msgid "日志版本文件没找到，请联系管理员"
msgstr ""

#: version_log/views.py:69
msgid "日志详情获取成功"
msgstr ""
